/* ============================================================
   分级词书  window.ED
   层级: 1 基础重建 · 2 高中核心 · 3 专升本高频
   词条: [单词, 词性, 释义(考试常用义)]
   ============================================================ */
(function (g) {
  var W = {
    tiers: [
      { id: 1, name: '基础重建', desc: '初中~高中基础 · 目标 50→80 分', color: '#0ea5e9', count: 0 },
      { id: 2, name: '高中核心', desc: '高考核心 · 目标 80→110 分', color: '#0ea56a', count: 0 },
      { id: 3, name: '专升本高频', desc: '真题高频 · 目标 110→150 分', color: '#7c3aed', count: 0 }
    ],
    list: []
  };
  // tier 1 —— 基础重建
  var L1 = [
    ["able","adj.","能够的"],["about","prep.","关于;大约"],["above","prep.","在…上方"],["accept","v.","接受"],
    ["across","prep.","穿过;在对面"],["act","v.","行动;表演"],["active","adj.","积极的;活跃的"],["add","v.","加;增添"],
    ["address","n.","地址"],["advice","n.","建议"],["afraid","adj.","害怕的;担心的"],["again","adv.","再次"],
    ["against","prep.","反对;倚靠"],["age","n.","年龄;时代"],["agree","v.","同意"],["air","n.","空气;天空"],
    ["allow","v.","允许"],["almost","adv.","几乎"],["alone","adj.","独自的"],["along","prep.","沿着"],
    ["already","adv.","已经"],["also","adv.","也"],["always","adv.","总是"],["among","prep.","在…之中"],
    ["angry","adj.","生气的"],["answer","n./v.","回答"],["appear","v.","出现;似乎"],["arrive","v.","到达"],
    ["ask","v.","问;请求"],["baby","n.","婴儿"],["bank","n.","银行;河岸"],["beat","v.","打败;敲打"],
    ["beautiful","adj.","美丽的"],["because","conj.","因为"],["become","v.","变成"],["begin","v.","开始"],
    ["behind","prep.","在…后面"],["believe","v.","相信"],["below","prep.","在…下面"],["between","prep.","在…之间"],
    ["borrow","v.","借入"],["both","pron.","两者都"],["bottle","n.","瓶子"],["bottom","n.","底部"],
    ["brave","adj.","勇敢的"],["bread","n.","面包"],["break","v.","打破;休息(n.)"],["bridge","n.","桥"],
    ["bright","adj.","明亮的;聪明的"],["bring","v.","带来"],["build","v.","建造"],["busy","adj.","忙碌的"],
    ["buy","v.","买"],["call","v.","打电话;称呼"],["capital","n.","首都;大写字母"],["care","v./n.","关心;小心"],
    ["careful","adj.","小心的"],["carry","v.","搬运;携带"],["catch","v.","抓住;赶上"],["cause","v.","导致 n.原因"],
    ["celebrate","v.","庆祝"],["center","n.","中心"],["chance","n.","机会;可能性"],["change","v./n.","改变;零钱"],
    ["cheap","adj.","便宜的"],["check","v.","检查"],["choose","v.","选择"],["city","n.","城市"],
    ["clean","adj./v.","干净的;打扫"],["clear","adj.","清楚的;晴朗的"],["clever","adj.","聪明的"],["climb","v.","爬"],
    ["close","v./adj.","关闭;近的"],["clothes","n.","衣服"],["club","n.","俱乐部"],["coffee","n.","咖啡"],
    ["cold","adj.","冷的 n.感冒"],["collect","v.","收集"],["color","n.","颜色"],["common","adj.","共同的;普通的"],
    ["computer","n.","电脑"],["cook","v.","做饭 n.厨师"],["cool","adj.","凉爽的;酷的"],["copy","v.","复制;抄写"],
    ["cost","n./v.","花费;成本"],["country","n.","国家;乡村"],["cover","v.","覆盖 n.封面"],["cross","v.","穿过"],
    ["cry","v.","哭;喊叫"],["cup","n.","杯子"],["cut","v.","切;割"],["dance","v./n.","跳舞;舞蹈"],
    ["danger","n.","危险"],["dark","adj.","黑暗的 n.黑暗"],["date","n.","日期"],["daughter","n.","女儿"],
    ["dead","adj.","死的"],["dear","adj.","亲爱的;昂贵的"],["decide","v.","决定"],["deep","adj.","深的"],
    ["develop","v.","发展;开发"],["die","v.","死"],["different","adj.","不同的"],["difficult","adj.","困难的"],
    ["dinner","n.","晚餐"],["dirty","adj.","脏的"],["discover","v.","发现"],["discuss","v.","讨论"],
    ["doctor","n.","医生;博士"],["double","adj.","双倍的"],["draw","v.","画;拉"],["dream","n./v.","梦想;做梦"],
    ["dress","v.","穿衣 n.连衣裙"],["drink","v.","喝 n.饮料"],["drive","v.","驾驶"],["drop","v.","掉落 n.滴"],
    ["dry","adj.","干燥的"],["during","prep.","在…期间"],["each","adj./pron.","每个"],["early","adj./adv.","早的;早"],
    ["earth","n.","地球;泥土"],["east","n.","东方"],["easy","adj.","容易的"],["eat","v.","吃"],
    ["egg","n.","鸡蛋"],["eight","num.","八"],["either","adv.","也(否定句)"],["else","adv.","其他;另外"],
    ["empty","adj.","空的"],["end","n./v.","结束;末端"],["enjoy","v.","享受;喜欢"],["enough","adj./adv.","足够的;足够地"],
    ["even","adv.","甚至"],["evening","n.","晚上"],["ever","adv.","曾经"],["every","adj.","每一个"],
    ["exam","n.","考试"],["example","n.","例子"],["excuse","n.","借口 v.原谅"],["exercise","n.","锻炼;练习"],
    ["expect","v.","期望"],["expensive","adj.","昂贵的"],["explain","v.","解释"],["eye","n.","眼睛"],
    ["face","n.","脸 v.面对"],["fact","n.","事实"],["fail","v.","失败"],["fair","adj.","公平的"],
    ["fall","v.","落下;跌倒"],["family","n.","家庭"],["famous","adj.","著名的"],["far","adj./adv.","远的;远"],
    ["farm","n.","农场"],["fast","adj./adv.","快的;快"],["fat","adj.","胖的"],["favorite","adj.","最喜爱的"],
    ["feed","v.","喂养"],["feel","v.","感觉"],["few","adj.","很少的"],["field","n.","田野;领域"],
    ["fight","v./n.","打架;战斗"],["fill","v.","装满"],["film","n.","电影;胶卷"],["find","v.","找到;发现"],
    ["finish","v.","完成"],["fire","n.","火"],["first","num.","第一"],["fish","n.","鱼 v.钓鱼"],
    ["fit","v./adj.","适合;健康的"],["flag","n.","旗帜"],["floor","n.","地板;楼层"],["fly","v.","飞;乘飞机"],
    ["follow","v.","跟随;遵循"],["food","n.","食物"],["foot","n.","脚;英尺"],["foreign","adj.","外国的"],
    ["forget","v.","忘记"],["free","adj.","自由的;免费的"],["fresh","adj.","新鲜的"],["friend","n.","朋友"],
    ["front","n.","前面"],["fruit","n.","水果"],["full","adj.","满的;饱的"],["fun","n.","乐趣"],
    ["future","n.","未来"],["game","n.","游戏;比赛"],["garden","n.","花园"],["gate","n.","大门"],
    ["gift","n.","礼物;天赋"],["glad","adj.","高兴的"],["glass","n.","玻璃;玻璃杯"],["goal","n.","目标;进球"],
    ["grade","n.","年级;分数"],["grass","n.","草"],["great","adj.","伟大的;很好的"],["green","adj.","绿色的"],
    ["ground","n.","地面"],["group","n.","组;群"],["grow","v.","生长;种植;变得"],["guess","v.","猜"],
    ["hair","n.","头发"],["half","n.","一半"],["hand","n.","手 v.递交"],["happy","adj.","快乐的"],
    ["hard","adj./adv.","困难的;努力地"],["hate","v.","讨厌"],["head","n.","头 v.朝…去"],["health","n.","健康"],
    ["healthy","adj.","健康的"],["hear","v.","听见"],["heart","n.","心脏;内心"],["heavy","adj.","重的"],
    ["help","v./n.","帮助"],["high","adj.","高的"],["hill","n.","小山"],["hold","v.","握住;举行"],
    ["holiday","n.","假日"],["home","n.","家"],["hope","v./n.","希望"],["hospital","n.","医院"],
    ["hot","adj.","热的;辣的"],["hotel","n.","旅馆"],["hour","n.","小时"],["however","adv.","然而"],
    ["huge","adj.","巨大的"],["hungry","adj.","饥饿的"],["hurry","v./n.","匆忙"],["hurt","v.","伤害;疼"],
    ["idea","n.","主意;想法"],["ill","adj.","生病的"],["important","adj.","重要的"],["improve","v.","提高;改善"],
    ["include","v.","包括"],["increase","v./n.","增加"],["interest","n.","兴趣;利益"],["interested","adj.","感兴趣的"],
    ["interesting","adj.","有趣的"],["internet","n.","互联网"],["introduce","v.","介绍"],["invite","v.","邀请"],
    ["island","n.","岛屿"],["job","n.","工作"],["join","v.","加入;参加"],["joke","n.","笑话"],
    ["jump","v.","跳"],["keep","v.","保持;保存"],["key","n.","钥匙;关键"],["kill","v.","杀死"],
    ["kind","adj.","友好的 n.种类"],["king","n.","国王"],["know","v.","知道;认识"],["knowledge","n.","知识"],
    ["lake","n.","湖泊"],["land","n.","陆地;土地"],["language","n.","语言"],["large","adj.","大的"],
    ["last","adj.","最后的;上一个"],["late","adj./adv.","迟的;晚"],["laugh","v.","笑"],["lazy","adj.","懒惰的"],
    ["learn","v.","学习;得知"],["leave","v.","离开;留下"],["left","adj.","左边的"],["lend","v.","借出"],
    ["lesson","n.","课;教训"],["letter","n.","信;字母"],["library","n.","图书馆"],["life","n.","生活;生命"],
    ["light","n.","光 adj.轻的"],["like","v.","喜欢 prep.像"],["line","n.","线;排;台词"],["list","n.","清单"],
    ["listen","v.","听"],["little","adj.","小的;少的"],["live","v.","居住;生活"],["local","adj.","当地的"],
    ["long","adj.","长的"],["look","v.","看;看起来"],["lose","v.","失去;输"],["lot","n.","许多"],
    ["loud","adj.","大声的"],["love","v./n.","爱"],["low","adj.","低的"],["lucky","adj.","幸运的"],
    ["lunch","n.","午餐"],["machine","n.","机器"],["mail","n.","邮件"],["main","adj.","主要的"],
    ["make","v.","制作;使得"],["map","n.","地图"],["market","n.","市场"],["marry","v.","结婚;嫁;娶"],
    ["match","n.","比赛;火柴 v.匹配"],["matter","n.","事情 v.要紧"],["meal","n.","一餐"],["mean","v.","意思是;打算"],
    ["meat","n.","肉"],["meet","v.","遇见;会面"],["meeting","n.","会议"],["member","n.","成员"],
    ["memory","n.","记忆"],["message","n.","消息;信息"],["middle","n.","中间"],["milk","n.","牛奶"],
    ["mind","n.","头脑 v.介意"],["minute","n.","分钟"],["miss","v.","错过;想念"],["mistake","n.","错误"],
    ["modern","adj.","现代的"],["moment","n.","时刻"],["money","n.","钱"],["month","n.","月份"],
    ["moon","n.","月亮"],["morning","n.","早晨"],["most","adj./adv.","最多的;最"],["mother","n.","母亲"],
    ["mountain","n.","山"],["mouth","n.","嘴"],["move","v.","移动;搬家"],["movie","n.","电影"],
    ["much","adj./adv.","许多;非常"],["music","n.","音乐"],["narrow","adj.","狭窄的"],["near","prep.","在…附近"],
    ["necessary","adj.","必要的"],["need","v./n.","需要"],["never","adv.","从不"],["news","n.","新闻"],
    ["newspaper","n.","报纸"],["next","adj.","下一个的"],["nice","adj.","好的;友好的"],["night","n.","夜晚"],
    ["noise","n.","噪音"],["noon","n.","中午"],["north","n.","北方"],["nose","n.","鼻子"],
    ["note","n.","笔记;便条"],["nothing","pron.","没有什么"],["notice","v.","注意到 n.通知"],["number","n.","数字;号码"],
    ["nurse","n.","护士"],["ocean","n.","海洋"],["office","n.","办公室"],["often","adv.","经常"],
    ["old","adj.","老的;旧的"],["once","adv.","一次;曾经"],["only","adv./adj.","只;唯一的"],["open","v.","打开 adj.开着的"],
    ["opinion","n.","意见;看法"],["opposite","adj.","相反的;对面的"],["order","n.","命令;顺序 v.订购"],["other","adj.","其他的"],
    ["outside","adv.","在外面"],["own","adj./v.","自己的;拥有"],["page","n.","页"],["paint","v.","油漆;绘画"],
    ["pair","n.","一双;一对"],["paper","n.","纸;论文;试卷"],["parent","n.","父(母)亲"],["park","n.","公园 v.停车"],
    ["part","n.","部分;角色"],["party","n.","聚会;政党"],["pass","v.","通过;传递"],["past","n./prep.","过去;经过"],
    ["patient","n.","病人 adj.耐心的"],["pay","v.","支付 n.工资"],["peace","n.","和平;安宁"],["person","n.","人"],
    ["phone","n.","电话"],["photo","n.","照片"],["pick","v.","挑选;采摘"],["picture","n.","图片;照片"],
    ["piece","n.","块;片;张"],["place","n.","地方 v.放置"],["plan","n./v.","计划"],["plane","n.","飞机"],
    ["plant","n.","植物 v.种植"],["play","v.","玩;演奏;扮演"],["player","n.","运动员;播放器"],["please","v.","请;使高兴"],
    ["pocket","n.","口袋"],["point","n.","要点;分数 v.指"],["police","n.","警察"],["polite","adj.","有礼貌的"],
    ["pool","n.","水池"],["poor","adj.","贫穷的;差的"],["popular","adj.","受欢迎的;流行的"],["possible","adj.","可能的"],
    ["practice","n./v.","练习"],["prefer","v.","更喜欢"],["prepare","v.","准备"],["present","n.","礼物 adj.现在的;出席的"],
    ["pretty","adj.","漂亮的 adv.相当"],["price","n.","价格"],["print","v.","打印;印刷"],["prize","n.","奖品"],
    ["probably","adv.","很可能"],["problem","n.","问题"],["produce","v.","生产"],["program","n.","节目;程序;计划"],
    ["progress","n.","进步"],["promise","v./n.","承诺"],["protect","v.","保护"],["proud","adj.","自豪的"],
    ["public","adj.","公共的 n.公众"],["pull","v.","拉"],["push","v.","推"],["put","v.","放"],
    ["question","n.","问题 v.质疑"],["quick","adj.","快的"],["quiet","adj.","安静的"],["quite","adv.","相当;很"],
    ["race","n.","赛跑;种族"],["radio","n.","收音机"],["rain","n./v.","雨;下雨"],["raise","v.","举起;提高;筹集"],
    ["rather","adv.","相当;宁愿"],["reach","v.","到达;伸手够到"],["read","v.","阅读"],["ready","adj.","准备好的"],
    ["real","adj.","真的;现实的"],["really","adv.","真正地;确实"],["reason","n.","原因"],["receive","v.","收到"],
    ["record","n.","记录;唱片 v.记录"],["red","adj.","红色的"],["remember","v.","记得"],["remind","v.","提醒"],
    ["repair","v./n.","修理"],["repeat","v.","重复"],["reply","v./n.","回答;回复"],["report","n./v.","报道;报告"],
    ["rest","n.","休息;剩余部分"],["restaurant","n.","餐馆"],["result","n.","结果"],["return","v.","返回;归还"],
    ["rice","n.","大米;米饭"],["rich","adj.","富有的;丰富的"],["ride","v.","骑;乘"],["right","adj.","正确的;右边的"],
    ["ring","v.","(铃)响 n.戒指"],["rise","v.","上升;起床"],["river","n.","河流"],["road","n.","道路"],
    ["room","n.","房间;空间"],["rule","n.","规则 v.统治"],["run","v.","跑;经营"],["sad","adj.","悲伤的"],
    ["safe","adj.","安全的"],["same","adj.","相同的"],["save","v.","拯救;节省;储蓄"],["school","n.","学校"],
    ["science","n.","科学"],["sea","n.","大海"],["search","v./n.","搜索;搜寻"],["season","n.","季节"],
    ["seat","n.","座位"],["second","num.","第二 n.秒"],["secret","n.","秘密"],["see","v.","看见;明白"],
    ["seem","v.","似乎"],["sell","v.","卖"],["send","v.","发送;派遣"],["sentence","n.","句子;判决"],
    ["serious","adj.","严肃的;严重的"],["serve","v.","服务;提供"],["several","adj.","几个的"],["shake","v.","摇动;握手"],
    ["shape","n.","形状"],["share","v.","分享;共用"],["sheep","n.","羊"],["ship","n.","轮船 v.运送"],
    ["shirt","n.","衬衫"],["shoe","n.","鞋"],["shop","n.","商店 v.购物"],["short","adj.","短的;矮的"],
    ["shout","v.","喊叫"],["show","v.","展示 n.表演"],["sick","adj.","生病的;恶心的"],["side","n.","边;侧面"],
    ["simple","adj.","简单的"],["sing","v.","唱歌"],["single","adj.","单一的;单身的"],["sister","n.","姐妹"],
    ["sit","v.","坐"],["situation","n.","情况;形势"],["size","n.","尺寸;大小"],["skill","n.","技能"],
    ["sleep","v./n.","睡觉"],["slow","adj.","慢的"],["small","adj.","小的"],["smart","adj.","聪明的"],
    ["smell","v.","闻;闻起来 n.气味"],["smile","v./n.","微笑"],["snow","n./v.","雪;下雪"],["soft","adj.","软的;柔和的"],
    ["solve","v.","解决"],["son","n.","儿子"],["song","n.","歌曲"],["soon","adv.","不久;很快"],
    ["sorry","adj.","抱歉的"],["sound","n.","声音 v.听起来"],["south","n.","南方"],["space","n.","空间;太空"],
    ["speak","v.","说;讲"],["special","adj.","特殊的;专门的"],["speech","n.","演讲"],["speed","n.","速度"],
    ["spend","v.","花费(时间/钱)"],["sport","n.","运动"],["spring","n.","春天;泉水"],["stand","v.","站立;忍受"],
    ["star","n.","星星;明星"],["start","v.","开始"],["station","n.","车站;电台"],["stay","v.","停留;保持"],
    ["step","n.","步骤;台阶"],["still","adv.","仍然"],["stone","n.","石头"],["stop","v.","停止"],
    ["store","n.","商店 v.储存"],["story","n.","故事"],["straight","adj./adv.","直的;直接"],["strange","adj.","奇怪的;陌生的"],
    ["street","n.","街道"],["strong","adj.","强壮的;坚固的"],["student","n.","学生"],["study","v.","学习 n.书房;研究"],
    ["subject","n.","科目;主题"],["succeed","v.","成功"],["success","n.","成功"],["such","adj.","这样的"],
    ["sudden","adj.","突然的"],["suggest","v.","建议;暗示"],["summer","n.","夏天"],["sun","n.","太阳"],
    ["sunny","adj.","晴朗的"],["support","v./n.","支持;支撑"],["sure","adj.","确信的"],["surprise","n.","惊喜 v.使惊讶"],
    ["sweet","adj.","甜的 n.糖果"],["swim","v.","游泳"],["table","n.","桌子;表格"],["take","v.","拿;带走;花费"],
    ["talk","v.","谈话"],["tall","adj.","高的"],["taste","v.","尝起来 n.味道"],["teach","v.","教"],
    ["teacher","n.","教师"],["team","n.","团队"],["telephone","n.","电话"],["tell","v.","告诉;分辨"],
    ["temperature","n.","温度"],["term","n.","学期;术语"],["terrible","adj.","可怕的;糟糕的"],["test","n./v.","测试;检验"],
    ["thank","v.","感谢"],["think","v.","思考;认为"],["thirsty","adj.","口渴的"],["throw","v.","扔"],
    ["ticket","n.","票"],["time","n.","时间;次数"],["tired","adj.","疲倦的"],["today","adv./n.","今天"],
    ["together","adv.","一起"],["tomorrow","adv./n.","明天"],["tonight","adv.","今晚"],["tool","n.","工具"],
    ["tooth","n.","牙齿"],["top","n.","顶部;顶端"],["touch","v.","触摸;感动"],["tourist","n.","游客"],
    ["town","n.","城镇"],["train","n.","火车 v.训练"],["travel","v./n.","旅行"],["tree","n.","树"],
    ["trip","n.","旅行"],["trouble","n.","麻烦;问题"],["true","adj.","真的;真实的"],["trust","v./n.","信任"],
    ["truth","n.","真相"],["try","v.","尝试;努力"],["turn","v.","转动;转变 n.轮流"],["twice","adv.","两次;两倍"],
    ["type","n.","类型 v.打字"],["ugly","adj.","丑陋的"],["uncle","n.","叔叔;舅舅"],["under","prep.","在…下面"],
    ["understand","v.","理解"],["university","n.","大学"],["until","prep./conj.","直到"],["upstairs","adv.","在楼上"],
    ["use","v.","使用"],["useful","adj.","有用的"],["usual","adj.","通常的"],["usually","adv.","通常"],
    ["vacation","n.","假期"],["vegetable","n.","蔬菜"],["very","adv.","非常"],["village","n.","村庄"],
    ["visit","v./n.","参观;拜访"],["voice","n.","嗓音;声音"],["wait","v.","等待"],["wake","v.","醒来;唤醒"],
    ["walk","v./n.","走路;散步"],["wall","n.","墙"],["want","v.","想要"],["warm","adj.","温暖的"],
    ["wash","v.","洗"],["watch","v.","观看 n.手表"],["water","n.","水 v.浇水"],["way","n.","方式;道路"],
    ["weak","adj.","弱的;虚弱的"],["wear","v.","穿;戴"],["weather","n.","天气"],["week","n.","星期"],
    ["weekend","n.","周末"],["welcome","v./adj.","欢迎;受欢迎的"],["well","adv.","好;健康地"],["west","n.","西方"],
    ["wet","adj.","湿的"],["whole","adj.","整个的"],["wide","adj.","宽的;广泛的"],["wife","n.","妻子"],
    ["win","v.","赢;获胜"],["wind","n.","风"],["window","n.","窗户"],["winter","n.","冬天"],
    ["wise","adj.","明智的;聪明的"],["wish","v./n.","希望;祝愿"],["without","prep.","没有"],["woman","n.","女人"],
    ["wonder","v.","想知道 n.奇迹"],["wonderful","adj.","精彩的;极好的"],["wood","n.","木头;树林"],["word","n.","单词;话语"],
    ["work","v.","工作;起作用 n.工作"],["worker","n.","工人"],["world","n.","世界"],["worry","v.","担心"],
    ["worse","adj.","更糟的"],["worst","adj.","最糟的"],["write","v.","写"],["wrong","adj.","错误的"],
    ["yard","n.","院子;码"],["year","n.","年"],["yellow","adj.","黄色的"],["yesterday","adv./n.","昨天"],
    ["young","adj.","年轻的"],["zero","num.","零"],["zoo","n.","动物园"]
  ];
  // tier 2 —— 高中核心
  var L2 = [
    ["abroad","adv.","在国外"],["accident","n.","事故;意外"],["achieve","v.","实现;达到"],["actually","adv.","实际上"],
    ["advantage","n.","优势;好处"],["adventure","n.","冒险"],["advertise","v.","做广告"],["affect","v.","影响"],
    ["afford","v.","负担得起"],["agency","n.","代理机构"],["agriculture","n.","农业"],["aim","n.","目标 v.瞄准"],
    ["amaze","v.","使惊奇"],["ambition","n.","雄心;抱负"],["amount","n.","数量;总额"],["amuse","v.","逗乐"],
    ["ancient","adj.","古代的"],["announce","v.","宣布"],["annual","adj.","每年的"],["anxious","adj.","焦虑的;渴望的"],
    ["apologize","v.","道歉"],["application","n.","申请;应用"],["apply","v.","申请;应用;涂"],["appreciate","v.","感激;欣赏"],
    ["approach","v.","接近 n.方法"],["approve","v.","赞成;批准"],["argue","v.","争论;主张"],["arise","v.","出现;产生"],
    ["arrange","v.","安排;整理"],["artificial","adj.","人造的"],["ashamed","adj.","羞愧的"],["assess","v.","评估"],
    ["assist","v.","协助"],["associate","v.","联系"],["assume","v.","假定"],["athlete","n.","运动员"],
    ["atmosphere","n.","气氛;大气"],["attach","v.","附上;系上"],["attempt","n./v.","尝试;企图"],["attend","v.","出席;照顾"],
    ["attitude","n.","态度"],["attract","v.","吸引"],["audience","n.","观众;听众"],["authority","n.","权威;当局"],
    ["available","adj.","可获得的;有空的"],["average","n./adj.","平均(的)"],["avoid","v.","避免"],["award","n.","奖 v.授予"],
    ["aware","adj.","意识到的"],["background","n.","背景"],["balance","n.","平衡 v.使平衡"],["ban","v./n.","禁止"],
    ["bargain","n.","便宜货 v.讨价还价"],["battle","n.","战役;斗争"],["behave","v.","表现"],["belief","n.","信念;信仰"],
    ["belong","v.","属于"],["benefit","n.","利益 v.有益于"],["besides","prep.","除…之外(还)"],["beyond","prep.","超出;在…之外"],
    ["blame","v.","责备 n.责任"],["blank","adj.","空白的 n.空格"],["bless","v.","保佑;祝福"],["block","n.","街区 v.阻塞"],
    ["bloom","v.","开花"],["bother","v.","打扰;费心"],["bound","adj.","必定会;被束缚的"],["branch","n.","树枝;分支;分公司"],
    ["brand","n.","品牌"],["breathe","v.","呼吸"],["brief","adj.","简短的"],["brilliant","adj.","杰出的;明亮的"],
    ["broad","adj.","宽广的"],["broadcast","n./v.","广播;播放"],["budget","n.","预算"],["burden","n.","负担"],
    ["burst","v.","爆裂;突然出现"],["calculate","v.","计算"],["calm","adj.","镇静的;平静的"],["campaign","n.","运动;战役"],
    ["cancel","v.","取消"],["candidate","n.","候选人;考生"],["capable","adj.","有能力的"],["capacity","n.","容量;能力"],
    ["capture","v.","捕获;夺取"],["career","n.","职业;生涯"],["cautious","adj.","谨慎的"],["cease","v.","停止"],
    ["challenge","n.","挑战"],["champion","n.","冠军"],["character","n.","性格;角色;人物"],["characteristic","n.","特征 adj.典型的"],
    ["charge","v.","收费;充电 n.费用;掌管"],["charity","n.","慈善(机构)"],["chart","n.","图表"],["cheat","v.","作弊;欺骗"],
    ["chemical","adj.","化学的 n.化学品"],["chief","adj.","主要的 n.首领"],["circumstance","n.","环境;情况"],
    ["claim","v.","声称;索取"],["clarify","v.","澄清;阐明"],["classic","adj.","经典的"],["climate","n.","气候"],
    ["colleague","n.","同事"],["combine","v.","结合"],["comfort","n./v.","安慰;舒适"],["command","n./v.","命令;掌握"],
    ["comment","n./v.","评论"],["commercial","adj.","商业的"],["commit","v.","犯(错);承诺"],["communicate","v.","交流;传达"],
    ["community","n.","社区;社会"],["compare","v.","比较"],["compete","v.","竞争"],["competent","adj.","有能力的"],
    ["complain","v.","抱怨"],["complex","adj.","复杂的"],["component","n.","组成部分"],["compose","v.","组成;创作"],
    ["concentrate","v.","集中(注意力)"],["concept","n.","概念"],["concern","v.","涉及;使担心"],["conclude","v.","得出结论;结束"],
    ["conduct","v.","进行;指挥 n.行为"],["confident","adj.","自信的"],["confirm","v.","证实;确认"],["conflict","n.","冲突"],
    ["confuse","v.","使困惑"],["congratulate","v.","祝贺"],["connect","v.","连接;联系"],["conscious","adj.","有意识的;清醒的"],
    ["consequence","n.","后果"],["consider","v.","考虑;认为"],["consist","v.","由…组成"],["constant","adj.","持续的;不变的"],
    ["construct","v.","建造;构建"],["consult","v.","咨询;查阅"],["consume","v.","消费;消耗"],["contact","n./v.","联系;接触"],
    ["contain","v.","包含"],["contemporary","adj.","当代的"],["content","n.","内容;目录 adj.满足的"],["contest","n.","竞赛"],
    ["context","n.","上下文;背景"],["continent","n.","大陆;洲"],["contract","n.","合同"],["contrary","adj.","相反的 n.相反"],
    ["contribute","v.","贡献;捐助"],["convenient","adj.","方便的"],["convince","v.","说服;使信服"],["cooperate","v.","合作"],
    ["cope","v.","应对;对付"],["courage","n.","勇气"],["crash","v.","碰撞;坠毁 n.事故"],["creative","adj.","有创造力的"],
    ["creature","n.","生物;动物"],["credit","n.","信用;学分;功劳"],["crime","n.","犯罪"],["crisis","n.","危机"],
    ["critic","n.","批评家"],["critical","adj.","批判的;关键的"],["criticize","v.","批评"],["crowd","n.","人群 v.挤满"],
    ["cruel","adj.","残忍的"],["cultivate","v.","培养;耕作"],["curiosity","n.","好奇心"],["current","adj.","当前的 n.水流;电流"],
    ["custom","n.","风俗;海关"],["cycle","n.","循环;自行车"],["daily","adj.","每日的"],["damage","n./v.","损害"],
    ["deadline","n.","截止日期"],["debate","n./v.","辩论"],["debt","n.","债务"],["decade","n.","十年"],
    ["decline","v./n.","下降;谢绝"],["decorate","v.","装饰"],["decrease","v./n.","减少"],["dedicate","v.","奉献;致力于"],
    ["defeat","v.","击败 n.失败"],["defend","v.","保卫;辩护"],["definite","adj.","明确的"],["delay","v./n.","延迟;耽搁"],
    ["deliver","v.","递送;发表(演讲)"],["demand","v./n.","要求;需求"],["demonstrate","v.","证明;示范"],["deny","v.","否认"],
    ["depart","v.","离开;出发"],["depend","v.","依靠;取决于"],["depress","v.","使沮丧"],["describe","v.","描述"],
    ["desert","n.","沙漠 v.抛弃"],["deserve","v.","应得"],["desire","n./v.","渴望;欲望"],["desperate","adj.","绝望的;不顾一切的"],
    ["destination","n.","目的地"],["destroy","v.","摧毁"],["detect","v.","察觉;探测"],["determine","v.","决定;下决心"],
    ["device","n.","设备;装置"],["devote","v.","献身;致力于"],["diet","n.","饮食"],["differ","v.","不同;相异"],
    ["digital","adj.","数字的"],["disappoint","v.","使失望"],["disaster","n.","灾难"],["discipline","n.","纪律;学科"],
    ["discount","n.","折扣"],["discourage","v.","使气馁;劝阻"],["disease","n.","疾病"],["dismiss","v.","解雇;不予理会"],
    ["display","n./v.","展示;陈列"],["distance","n.","距离"],["distinct","adj.","明显不同的"],["distribute","v.","分发;分布"],
    ["district","n.","地区;区域"],["disturb","v.","打扰;使不安"],["diverse","adj.","多样的"],["divorce","n./v.","离婚"],
    ["document","n.","文件"],["dominate","v.","支配;占优势"],["donate","v.","捐赠"],["doubt","n./v.","怀疑"],
    ["draft","n.","草稿 v.起草"],["dramatic","adj.","戏剧性的;巨大的"],["due","adj.","到期的;应有的"],["dull","adj.","枯燥的;迟钝的"],
    ["eager","adj.","渴望的"],["earn","v.","赚得;赢得"],["economic","adj.","经济的"],["economy","n.","经济"],
    ["edge","n.","边缘;优势"],["edit","v.","编辑"],["educate","v.","教育"],["effective","adj.","有效的"],
    ["efficient","adj.","高效的"],["effort","n.","努力"],["elderly","adj.","年长的"],["elect","v.","选举"],
    ["electric","adj.","电的"],["electronic","adj.","电子的"],["element","n.","要素;元素"],["eliminate","v.","消除;淘汰"],
    ["embarrass","v.","使尴尬"],["emerge","v.","出现;显现"],["emergency","n.","紧急情况"],["emotion","n.","情感"],
    ["emphasis","n.","强调;重点"],["emphasize","v.","强调"],["employ","v.","雇用;使用"],["enable","v.","使能够"],
    ["encounter","v./n.","遭遇;邂逅"],["encourage","v.","鼓励"],["energy","n.","能量;精力"],["engage","v.","从事;订婚;吸引"],
    ["engine","n.","发动机;引擎"],["enhance","v.","提高;增强"],["enormous","adj.","巨大的"],["entertain","v.","娱乐;招待"],
    ["enthusiasm","n.","热情;热心"],["entire","adj.","全部的"],["entry","n.","进入;条目"],["environment","n.","环境"],
    ["equal","adj.","平等的 v.等于"],["equip","v.","装备"],["error","n.","错误"],["escape","v.","逃跑;逃脱"],
    ["especially","adv.","尤其"],["essay","n.","文章;散文"],["essential","adj.","必不可少的"],["establish","v.","建立;确立"],
    ["estimate","v./n.","估计"],["evaluate","v.","评价;评估"],["eventually","adv.","最终"],["evident","adj.","明显的"],
    ["evolve","v.","进化;演变"],["exaggerate","v.","夸大"],["examine","v.","检查;考试"],["exceed","v.","超过"],
    ["excellent","adj.","极好的"],["exchange","v./n.","交换;交流"],["excite","v.","使兴奋"],["exhibit","v.","展览"],
    ["exist","v.","存在"],["expand","v.","扩大;膨胀"],["expense","n.","费用;花费"],["expert","n.","专家 adj.熟练的"],
    ["explore","v.","探索;探险"],["export","n./v.","出口"],["expose","v.","暴露;揭露"],["express","v.","表达"],
    ["extend","v.","延伸;扩展"],["extent","n.","程度;范围"],["extreme","adj.","极端的"],["factor","n.","因素"],
    ["fade","v.","褪色;逐渐消失"],["faith","n.","信念;信任"],["familiar","adj.","熟悉的"],["fancy","adj.","花哨的 v.想要;喜爱"],
    ["fantastic","adj.","极好的;奇异的"],["fare","n.","车费"],["fascinate","v.","使着迷"],["fashion","n.","时尚;方式"],
    ["fault","n.","过错;缺点"],["favor","n.","恩惠;赞同 v.支持"],["feature","n.","特征;特色"],["fee","n.","费用;学费"],
    ["fellow","n.","同伴;家伙"],["female","adj.","女性的 n.女性"],["festival","n.","节日"],["fierce","adj.","凶猛的;激烈的"],
    ["figure","n.","数字;人物;身材 v.认为"],["finance","n.","财政;金融"],["firm","n.","公司 adj.坚定的"],["flash","v.","闪光 n.闪光"],
    ["flexible","adj.","灵活的;柔韧的"],["flight","n.","航班;飞行"],["flood","n.","洪水 v.淹没"],["fluent","adj.","流利的"],
    ["focus","v.","集中 n.焦点"],["forbid","v.","禁止"],["force","v.","强迫 n.力量"],["forecast","n./v.","预测"],
    ["forgive","v.","原谅"],["formal","adj.","正式的"],["former","adj.","以前的;前者"],["fortune","n.","财富;运气"],
    ["frequent","adj.","频繁的"],["function","n.","功能;作用 v.运转"],["fundamental","adj.","基本的"],["furthermore","adv.","此外"],
    ["gain","v.","获得;增加"],["gap","n.","缺口;差距"],["gather","v.","聚集;收集"],["generate","v.","产生;发电"],
    ["generous","adj.","慷慨的"],["genius","n.","天才"],["genuine","adj.","真正的;真诚的"],["gesture","n.","手势;姿态"],
    ["glance","v./n.","瞥一眼"],["global","adj.","全球的"],["glory","n.","荣耀"],["govern","v.","统治;管理"],
    ["grab","v.","抓取;抢夺"],["gradual","adj.","逐渐的"],["graduate","v.","毕业 n.毕业生"],["grand","adj.","宏伟的"],
    ["grant","v.","授予;同意 n.拨款"],["grasp","v.","抓住;理解"],["grateful","adj.","感激的"],["greet","v.","问候;迎接"],
    ["guarantee","v./n.","保证"],["guilty","adj.","内疚的;有罪的"],["habit","n.","习惯"],["handle","v.","处理 n.把手"],
    ["harm","n./v.","伤害;危害"],["harvest","n./v.","收获;收割"],["heal","v.","治愈;愈合"],["height","n.","高度"],
    ["hesitate","v.","犹豫"],["highlight","v.","强调;突出 n.亮点"],["hire","v.","雇用;租用"],["historic","adj.","有历史意义的"],
    ["honor","n.","荣誉;尊敬 v.尊敬"],["host","n.","主人;主持人"],["household","n.","家庭;家务"],["humor","n.","幽默"],
    ["hunt","v.","打猎;搜寻"],["ideal","adj.","理想的 n.理想"],["identical","adj.","完全相同的"],["identify","v.","识别;确认"],
    ["ignore","v.","忽视;不理会"],["illegal","adj.","非法的"],["illustrate","v.","说明;举例说明"],["image","n.","形象;图像"],
    ["imitate","v.","模仿"],["immediate","adj.","立即的;直接的"],["immigrant","n.","移民"],["impact","n.","影响;冲击"],
    ["imply","v.","暗示;意味着"],["import","n./v.","进口"],["impress","v.","给…留下印象"],["incident","n.","事件"],
    ["income","n.","收入"],["independent","adj.","独立的"],["indicate","v.","表明;指出"],["individual","n.","个人 adj.个人的"],
    ["industry","n.","工业;行业"],["inevitable","adj.","不可避免的"],["infer","v.","推断"],["influence","n./v.","影响"],
    ["inform","v.","通知"],["ingredient","n.","成分;原料"],["initial","adj.","最初的"],["injure","v.","使受伤"],
    ["innocent","adj.","无辜的;天真的"],["insist","v.","坚持"],["inspire","v.","鼓舞;激发"],["instance","n.","例子;实例"],
    ["instant","adj.","立即的 n.瞬间"],["institute","n.","学院;研究所"],["instruct","v.","指导;指示"],["instrument","n.","乐器;仪器"],
    ["insure","v.","给…保险;确保"],["intend","v.","打算;意图"],["intense","adj.","强烈的;紧张的"],["interact","v.","互动;相互作用"],
    ["interfere","v.","干涉;干扰"],["interpret","v.","解释;口译"],["interrupt","v.","打断;中断"],["interview","n./v.","面试;采访"],
    ["invade","v.","入侵"],["invent","v.","发明;编造"],["invest","v.","投资"],["investigate","v.","调查"],
    ["involve","v.","涉及;使参与"],["isolate","v.","孤立;隔离"],["issue","n.","问题;发行 v.发布"],["item","n.","项目;条款;一件物品"],
    ["jealous","adj.","嫉妒的"],["journal","n.","杂志;日记"],["journey","n.","旅行;旅程"],["judge","v.","判断;审判 n.法官"],
    ["justice","n.","正义;公正"],["keen","adj.","渴望的;敏锐的"],["label","n.","标签 v.贴标签"],["lack","n./v.","缺乏"],
    ["launch","v.","发射;发起"],["law","n.","法律"],["lean","v.","倾斜;依靠"],["legal","adj.","合法的"],
    ["length","n.","长度"],["level","n.","水平;等级"],["liable","adj.","易于…的;可能的"],["license","n.","执照;许可证"],
    ["likely","adj./adv.","可能的;很可能"],["limit","v.","限制 n.限度"],["link","n./v.","联系;连接"],["liquid","n.","液体 adj.液态的"],
    ["literature","n.","文学"],["load","n.","负荷 v.装载"],["loan","n.","贷款 v.借出"],["locate","v.","位于;找到"],
    ["loose","adj.","松的;宽松的"],["loyal","adj.","忠诚的"],["maintain","v.","维持;保养;坚持认为"],["major","adj.","主要的 n.专业"],
    ["manage","v.","管理;设法做到"],["manner","n.","方式;礼貌"],["manufacture","v.","制造 n.制造"],["massive","adj.","巨大的"],
    ["material","n.","材料;资料 adj.物质的"],["mature","adj.","成熟的"],["maximum","n./adj.","最大(的)"],["means","n.","方法;手段"],
    ["measure","v.","测量 n.措施"],["media","n.","媒体"],["medical","adj.","医学的"],["medium","adj.","中等的 n.媒介"],
    ["mental","adj.","精神的;心理的"],["mention","v.","提到"],["mercy","n.","仁慈;怜悯"],["merely","adv.","仅仅"],
    ["migrate","v.","迁移;移居"],["mild","adj.","温和的;轻微的"],["military","adj.","军事的"],["minor","adj.","较小的;次要的"],
    ["mission","n.","使命;任务"],["mobile","adj.","可移动的;手机的"],["moderate","adj.","适度的;温和的"],["modify","v.","修改;调整"],
    ["monitor","v.","监控 n.显示器;班长"],["moral","adj.","道德的"],["motivate","v.","激励;激发"],["multiply","v.","乘;繁殖"],
    ["murder","v./n.","谋杀"],["mutual","adj.","相互的;共同的"],["mysterious","adj.","神秘的"],["native","adj.","本地的 n.本地人"],
    ["negative","adj.","消极的;否定的"],["neglect","v.","忽视;疏忽"],["negotiate","v.","谈判;协商"],["nervous","adj.","紧张的"],
    ["network","n.","网络"],["nevertheless","adv.","然而;不过"],["noble","adj.","高贵的;高尚的"],["nod","v.","点头"],
    ["normal","adj.","正常的"],["novel","n.","小说"],["numerous","adj.","许多的"],["nutrition","n.","营养"],
    ["objective","n.","目标 adj.客观的"],["oblige","v.","迫使;使感激"],["observe","v.","观察;遵守"],["obtain","v.","获得"],
    ["obvious","adj.","明显的"],["occasion","n.","场合;时机"],["occupy","v.","占据;占用"],["occur","v.","发生;想起"],
    ["odd","adj.","奇怪的;奇数的"],["operate","v.","操作;经营;动手术"],["opportunity","n.","机会"],["oppose","v.","反对"],
    ["optimistic","adj.","乐观的"],["option","n.","选择(权)"],["ordinary","adj.","普通的"],["organize","v.","组织"],
    ["origin","n.","起源;出身"],["otherwise","adv.","否则;在其他方面"],["outcome","n.","结果"],["outline","n.","大纲;轮廓 v.概述"],
    ["output","n.","产量;输出"],["outstanding","adj.","杰出的"],["overcome","v.","克服"],["overseas","adj./adv.","海外的;在海外"],
    ["pace","n.","步伐;速度"],["package","n.","包裹"],["participate","v.","参加"],["particular","adj.","特定的;特别的"],
    ["passion","n.","激情;热爱"],["passive","adj.","被动的"],["pattern","n.","模式;图案"],["pause","v./n.","暂停"],
    ["peculiar","adj.","奇怪的;特有的"],["peer","n.","同龄人;同辈"],["perceive","v.","感知;认为"],["percent","n.","百分之…"],
    ["performance","n.","表演;表现;性能"],["permanent","adj.","永久的"],["permission","n.","许可"],["permit","v.","允许 n.许可证"],
    ["persist","v.","坚持;持续"],["perspective","n.","视角;观点"],["persuade","v.","说服"],["phenomenon","n.","现象"],
    ["physical","adj.","身体的;物理的"],["pile","n.","堆 v.堆积"],["pioneer","n.","先驱;开拓者"],["pity","n.","同情;遗憾"],
    ["plain","adj.","清楚的;朴素的 n.平原"],["policy","n.","政策;方针"],["polish","v.","擦亮;润色"],["political","adj.","政治的"],
    ["pollution","n.","污染"],["portion","n.","部分;一份"],["portrait","n.","肖像;描写"],["pose","v.","造成;摆姿势"],
    ["positive","adj.","积极的;肯定的;阳性的"],["possess","v.","拥有;支配"],["potential","adj.","潜在的 n.潜力"],
    ["poverty","n.","贫困"],["powerful","adj.","强大的"],["practical","adj.","实际的;实用的"],["praise","n./v.","赞扬"],
    ["precious","adj.","珍贵的"],["precise","adj.","精确的"],["predict","v.","预言;预测"],["prejudice","n.","偏见"],
    ["presence","n.","出席;存在"],["preserve","v.","保护;保存"],["pressure","n.","压力"],["pretend","v.","假装"],
    ["previous","adj.","先前的"],["primarily","adv.","主要地"],["principle","n.","原则;原理"],["prior","adj.","先前的;优先的"],
    ["private","adj.","私人的"],["privilege","n.","特权;荣幸"],["procedure","n.","程序;步骤"],["process","n.","过程 v.处理"],
    ["profession","n.","职业;专业"],["profit","n.","利润;益处"],["prohibit","v.","禁止"],["project","n.","项目 v.投射;预计"],
    ["promote","v.","促进;晋升;推广"],["prompt","adj.","迅速的 v.促使"],["proportion","n.","比例;部分"],["proposal","n.","提议;求婚"],
    ["prosperity","n.","繁荣"],["protest","v./n.","抗议"],["provide","v.","提供"],["province","n.","省"],
    ["publish","v.","出版;发表"],["purchase","v.","购买 n.购买物"],["pursue","v.","追求;从事"],["qualify","v.","取得资格;使合格"],
    ["quantity","n.","数量"],["quote","v.","引用"],["range","n.","范围;一系列 v.变动"],["rare","adj.","稀有的;罕见的"],
    ["rate","n.","比率;速度 v.评价"],["raw","adj.","生的;未加工的"],["react","v.","反应;起化学反应"],["reality","n.","现实"],
    ["recall","v.","回忆起;召回"],["recover","v.","恢复;康复"],["reduce","v.","减少"],["refer","v.","提到;参考"],
    ["reflect","v.","反映;反思;反射"],["reform","n./v.","改革"],["refresh","v.","使恢复精神;刷新"],["regardless","adv.","不管怎样"],
    ["register","v.","登记;注册"],["regular","adj.","定期的;规则的"],["regulate","v.","管理;调节"],["reinforce","v.","加强;增援"],
    ["reject","v.","拒绝;排斥"],["relate","v.","联系;叙述"],["relative","n.","亲戚 adj.相对的"],["relax","v.","放松"],
    ["release","v.","释放;发行"],["relevant","adj.","相关的"],["relieve","v.","减轻;缓解"],["religion","n.","宗教"],
    ["rely","v.","依靠;信赖"],["remain","v.","保持;留下;仍然"],["remarkable","adj.","非凡的;显著的"],["remote","adj.","遥远的"],
    ["remove","v.","移除;脱掉"],["rent","n./v.","租金;租"],["replace","v.","取代;替换"],["represent","v.","代表;象征"],
    ["reputation","n.","名声;声誉"],["request","n./v.","请求;要求"],["require","v.","需要;要求"],["rescue","v./n.","营救"],
    ["reserve","v.","预订;保留 n.储备"],["resist","v.","抵抗;抵制"],["resolve","v.","解决;决心"],["resort","n.","度假胜地;手段"],
    ["resource","n.","资源"],["respond","v.","回应;作出反应"],["responsible","adj.","负责的"],["restore","v.","恢复;修复"],
    ["restrict","v.","限制"],["retain","v.","保留;保持"],["retire","v.","退休;退役"],["reveal","v.","揭示;透露"],
    ["reverse","v.","颠倒;倒车 adj.相反的"],["review","n./v.","复习;评论;审查"],["revise","v.","修订;复习"],["reward","n./v.","奖励;报酬"],
    ["rid","v.","使摆脱"],["risk","n.","风险 v.冒险"],["role","n.","角色;作用"],["routine","n.","常规;例行程序 adj.例行的"],
    ["ruin","v.","毁坏 n.废墟"],["rural","adj.","农村的"],["rush","v.","冲;匆忙"],["sacrifice","v./n.","牺牲"],
    ["salary","n.","薪水"],["sample","n.","样本;样品"],["satisfy","v.","使满意;满足"],["scale","n.","规模;比例;刻度"],
    ["scan","v.","扫描;浏览"],["scare","v.","使害怕"],["schedule","n.","时间表;日程"],["scholar","n.","学者"],
    ["score","n.","分数 v.得分"],["secure","adj.","安全的 v.获得;使安全"],["seek","v.","寻求;寻找"],["select","v.","选择"],
    ["senior","adj.","年长的;高级的"],["sense","n.","感觉;意义;理智"],["sensitive","adj.","敏感的;灵敏的"],["series","n.","系列;连续"],
    ["session","n.","一场;会议;一段时间"],["severe","adj.","严重的;严厉的"],["shelter","n.","庇护所;遮蔽 v.遮蔽"],
    ["shift","v.","转移;改变 n.轮班"],["shortage","n.","短缺"],["shrink","v.","收缩;缩小"],["significant","adj.","重要的;显著的"],
    ["sincere","adj.","真诚的"],["site","n.","地点;网站"],["slight","adj.","轻微的;纤细的"],["slip","v.","滑倒;溜走"],
    ["smooth","adj.","光滑的;顺利的"],["software","n.","软件"],["sole","adj.","唯一的 n.鞋底"],["solution","n.","解决办法;溶液"],
    ["somewhat","adv.","有点;稍微"],["sophisticated","adj.","复杂精密的;老练的"],["source","n.","来源;源头"],["specific","adj.","具体的;特定的"],
    ["specify","v.","具体说明"],["spirit","n.","精神;心灵;烈酒"],["split","v.","分裂;劈开"],["sponsor","v.","赞助 n.赞助商"],
    ["spot","n.","地点;斑点 v.发现"],["stable","adj.","稳定的"],["staff","n.","全体员工"],["stage","n.","阶段;舞台"],
    ["standard","n.","标准 adj.标准的"],["statement","n.","陈述;声明"],["status","n.","地位;状况"],["steady","adj.","稳定的;平稳的"],
    ["stimulate","v.","刺激;激励"],["strategy","n.","策略;战略"],["stress","n.","压力;强调 v.强调"],["strict","adj.","严格的"],
    ["structure","n.","结构;建筑物"],["struggle","v./n.","奋斗;挣扎"],["style","n.","风格;样式"],["submit","v.","提交;屈服"],
    ["sufficient","adj.","足够的"],["summary","n.","摘要;总结"],["supply","n.","供应;补给 v.供应"],["suppose","v.","假设;认为"],
    ["survey","n./v.","调查;测量"],["survive","v.","幸存;生存"],["suspect","v.","怀疑 n.嫌疑人"],["sustain","v.","维持;支撑"],
    ["swallow","v.","吞咽 n.燕子"],["symbol","n.","象征;符号"],["sympathy","n.","同情"],["symptom","n.","症状"],
    ["tackle","v.","处理;解决"],["talent","n.","天赋;人才"],["target","n.","目标;靶子 v.以…为目标"],["tax","n.","税"],
    ["temporary","adj.","临时的"],["tend","v.","倾向于;照料"],["tense","adj.","紧张的 n.时态"],["theme","n.","主题"],
    ["threat","n.","威胁"],["thus","adv.","因此"],["tolerate","v.","容忍"],["topic","n.","话题;主题"],
    ["tough","adj.","艰苦的;强硬的"],["trace","v.","追踪;追溯 n.痕迹"],["track","n.","轨道;跑道 v.追踪"],["tradition","n.","传统"],
    ["transfer","v.","转移;转学;换乘"],["transform","v.","使转变;改变"],["transport","n.","运输 v.运送"],["trend","n.","趋势"],
    ["trial","n.","试验;审判"],["trigger","v.","触发;引发 n.扳机"],["typical","adj.","典型的"],["ultimate","adj.","最终的;根本的"],
    ["undergo","v.","经历;遭受"],["underline","v.","在…下划线;强调"],["undertake","v.","承担;着手做"],["unique","adj.","独特的"],
    ["update","v.","更新 n.最新消息"],["urge","v.","敦促;催促 n.冲动"],["urgent","adj.","紧急的"],["vague","adj.","模糊的;含糊的"],
    ["vain","adj.","徒劳的;自负的"],["valid","adj.","有效的;正当的"],["valuable","adj.","有价值的;宝贵的"],["vary","v.","变化;不同"],
    ["vast","adj.","广阔的;巨大的"],["vehicle","n.","车辆;交通工具"],["venture","n.","冒险事业 v.冒险"],["verify","v.","核实;证明"],
    ["version","n.","版本;说法"],["via","prep.","经由;通过"],["victim","n.","受害者"],["victory","n.","胜利"],
    ["violent","adj.","暴力的;猛烈的"],["virtual","adj.","虚拟的;实际上"],["virtue","n.","美德;优点"],["visible","adj.","可见的"],
    ["vision","n.","视力;愿景;想象力"],["vital","adj.","至关重要的;有活力的"],["vivid","adj.","生动的;鲜明的"],["volunteer","n.","志愿者 v.自愿"],
    ["vote","v./n.","投票;选举"],["wage","n.","工资(常用复数)"],["wealth","n.","财富"],["weapon","n.","武器"],
    ["welfare","n.","福利;幸福"],["whisper","v.","低语;耳语"],["widespread","adj.","广泛的;普遍的"],["witness","n.","目击者 v.目击"],
    ["worthwhile","adj.","值得的"],["worthy","adj.","值得的;配得上的"]
  ];
  // tier 3 —— 专升本高频（公共英语真题高频）
  var L3 = [
    ["abandon","v.","放弃;抛弃"],["ability","n.","能力"],["abolish","v.","废除"],["absorb","v.","吸收;使专心"],
    ["abstract","adj.","抽象的"],["abundant","adj.","丰富的;充裕的"],["academic","adj.","学术的"],["accelerate","v.","加速"],
    ["accompany","v.","陪伴;伴随"],["accomplish","v.","完成;实现"],["account","n.","账户;叙述;原因(v.说明)"],["accumulate","v.","积累;积聚"],
    ["accurate","adj.","准确的"],["accuse","v.","指控;指责"],["accustomed","adj.","习惯的"],["acquire","v.","获得;习得"],
    ["adapt","v.","适应;改编"],["adequate","adj.","充足的;胜任的"],["adjust","v.","调整;适应"],["administration","n.","管理;行政部门"],
    ["admire","v.","钦佩;欣赏"],["admission","n.","准入;承认"],["adopt","v.","采纳;收养"],["advance","v./n.","前进;进展;提前"],
    ["advert","v.","提及"],["advisable","adj.","明智的;可取的"],["advocate","v.","提倡 n.拥护者"],["aesthetic","adj.","审美的"],
    ["agenda","n.","议程"],["aggressive","adj.","侵略的;好斗的;有进取心的"],["alarm","n.","警报;惊恐 v.使惊恐"],["alert","adj.","警觉的 v.使警觉"],
    ["allocate","v.","分配;拨给"],["alter","v.","改变;更改"],["alternative","n.","选择;备选方案 adj.可替代的"],["altitude","n.","海拔;高度"],
    ["amateur","n.","业余爱好者"],["ambiguous","adj.","模棱两可的"],["amend","v.","修改;修订"],["ample","adj.","充足的;宽敞的"],
    ["analogy","n.","类比;类推"],["analysis","n.","分析"],["anniversary","n.","周年纪念日"],["anticipate","v.","预期;预料"],
    ["anxiety","n.","焦虑;担心"],["apparent","adj.","明显的;表面上的"],["appeal","v.","呼吁;上诉;吸引 n.吸引力"],["appetite","n.","食欲;欲望"],
    ["applaud","v.","鼓掌;称赞"],["appoint","v.","任命;约定"],["appraisal","n.","评估;评价"],["apprehension","n.","忧虑;理解"],
    ["appropriate","adj.","恰当的"],["arbitrary","adj.","任意的;武断的"],["arouse","v.","唤起;激起"],["articulate","v.","清楚表达 adj.口齿清晰的"],
    ["ascend","v.","上升;攀登"],["aspect","n.","方面;外观"],["assemble","v.","集合;装配"],["assert","v.","断言;坚持主张"],
    ["assignment","n.","任务;作业;分配"],["assumption","n.","假定;假设"],["astonish","v.","使惊讶"],["attain","v.","达到;获得"],
    ["attribute","v.","把…归因于 n.属性"],["audible","adj.","听得见的"],["authentic","adj.","真实的;正宗的"],["automatic","adj.","自动的;无意识的"],
    ["autonomous","adj.","自治的;自主的"],["awkward","adj.","尴尬的;笨拙的"],["barrier","n.","障碍;屏障"],["basis","n.","基础;根据"],
    ["bear","v.","忍受;承担;生育"],["beforehand","adv.","事先"],["behalf","n.","代表(on behalf of)"],["behave","v.","表现"],
    ["beneficial","adj.","有益的"],["betray","v.","背叛;泄露"],["bewilder","v.","使迷惑"],["bias","n.","偏见 v.使有偏见"],
    ["bind","v.","捆绑;约束"],["bitter","adj.","苦的;痛苦的;激烈的"],["bleed","v.","流血"],["boast","v.","自夸 n.引以为豪的事物"],
    ["bold","adj.","大胆的;粗体的"],["boost","v./n.","促进;提高"],["boundary","n.","边界;界限"],["breakthrough","n.","突破"],
    ["bribe","v./n.","贿赂"],["brink","n.","边缘"],["brisk","adj.","轻快的;兴旺的"],["bulk","n.","大部分;体积"],
    ["bureaucracy","n.","官僚机构;官僚主义"],["bypass","v.","绕过 n.旁路"],["cabin","n.","小屋;船舱"],["cable","n.","电缆;缆绳;有线电视"],
    ["campus","n.","校园"],["canteen","n.","食堂"],["cargo","n.","货物"],["casual","adj.","随便的;偶然的;临时的"],
    ["category","n.","类别;种类"],["cater","v.","迎合;提供饮食"],["caution","n.","谨慎;警告 v.警告"],["ceiling","n.","天花板;上限"],
    ["cement","n.","水泥 v.巩固"],["ceremony","n.","典礼;仪式"],["certificate","n.","证书;执照"],["chaos","n.","混乱"],
    ["chapter","n.","章;回"],["cherish","v.","珍爱;怀有"],["chill","n.","寒冷;寒意 v.使变冷"],["chronic","adj.","慢性的;长期的"],
    ["circulate","v.","循环;流传"],["circumstance","n.","情况;环境"],["cite","v.","引用;引证"],["civil","adj.","公民的;民用的;文明的"],
    ["civilization","n.","文明"],["clarify","v.","澄清"],["clash","n./v.","冲突;撞击"],["classify","v.","分类;归类"],
    ["clause","n.","从句;条款"],["clue","n.","线索"],["coincide","v.","同时发生;一致"],["collapse","v./n.","倒塌;崩溃"],
    ["collision","n.","碰撞;冲突"],["column","n.","柱;专栏;纵队"],["commence","v.","开始"],["commerce","n.","商业;贸易"],
    ["commission","n.","委员会;佣金"],["commodity","n.","商品;日用品"],["compact","adj.","紧凑的 v.压缩"],["compatible","adj.","兼容的;相容的"],
    ["compensate","v.","补偿;赔偿"],["compel","v.","强迫;迫使"],["compile","v.","汇编;编纂"],
    ["complement","v.","补充 n.补充物"],["complicate","v.","使复杂化"],["compliment","n./v.","赞美;恭维"],["comply","v.","遵守;服从"],
    ["comprehensive","adj.","全面的;综合的"],["compress","v.","压缩;压紧"],["compromise","n./v.","妥协;折中"],["compulsory","adj.","强制的;必修的"],
    ["conceal","v.","隐藏;隐瞒"],["concede","v.","承认;让步"],["conceive","v.","构想;怀孕"],["concession","n.","让步;特许权"],
    ["concrete","adj.","具体的;混凝土的 n.混凝土"],["condemn","v.","谴责;判刑"],["condense","v.","浓缩;压缩"],["confess","v.","承认;坦白"],
    ["confine","v.","限制;禁闭"],["confront","v.","面对;对抗"],["congress","n.","国会;代表大会"],["conjunction","n.","连词;结合"],
    ["conquer","v.","征服;克服"],["conscience","n.","良心;良知"],["consent","n./v.","同意;准许"],["conserve","v.","保护;节约"],
    ["considerable","adj.","相当大的;重要的"],["consistent","adj.","一致的;始终如一的"],["console","v.","安慰"],["constitute","v.","构成;组成"],
    ["constitution","n.","宪法;构成"],["constraint","n.","约束;限制"],["constructive","adj.","建设性的"],["consultant","n.","顾问"],
    ["contaminate","v.","污染;弄脏"],["contemplate","v.","沉思;考虑"],["contempt","n.","轻视;蔑视"],["contend","v.","竞争;主张"],
    ["contradict","v.","反驳;与…矛盾"],["controversy","n.","争论;争议"],["conventional","adj.","传统的;常规的"],["conversely","adv.","相反地"],
    ["convert","v.","转变;转换"],["convey","v.","传达;运送"],["convict","v.","定罪 n.囚犯"],["coordinate","v.","协调 n.坐标"],
    ["corporate","adj.","公司的;法人的"],["correlate","v.","相互关联"],["correspond","v.","相符合;通信"],["corrupt","adj.","腐败的 v.腐蚀"],
    ["counsel","n.","忠告;法律顾问 v.劝告"],["counter","n.","柜台;计数器 v.反驳"],["courtesy","n.","礼貌;好意"],["craft","n.","工艺;手艺;飞行器"],
    ["credential","n.","凭证;资质"],["credible","adj.","可信的"],["criterion","n.","(评判)标准;准则"],["crucial","adj.","至关重要的"],
    ["crude","adj.","粗糙的;天然的"],["cue","n.","提示;暗示"],["cultivate","v.","培养;耕作"],["cumulative","adj.","累积的"],
    ["cure","v.","治愈 n.疗法"],["curb","v.","控制;抑制 n.路缘"],["curriculum","n.","课程(体系)"],["curse","n./v.","诅咒"],
    ["customary","adj.","习惯的;惯例的"],["cynical","adj.","愤世嫉俗的;怀疑的"],["dazzle","v.","使目眩;使惊叹"],["decay","v./n.","腐烂;衰退"],
    ["deceive","v.","欺骗"],["decent","adj.","体面的;正派的"],["decisive","adj.","决定性的;果断的"],["declaration","n.","宣言;声明"],
    ["deduct","v.","扣除;减去"],["deem","v.","认为;视为"],["default","n.","违约;默认 v.拖欠"],["defect","n.","缺点;缺陷"],
    ["defy","v.","违抗;藐视"],["deficiency","n.","缺乏;不足"],["degrade","v.","降低;贬低"],["delegate","n.","代表 v.委派"],
    ["deliberate","adj.","故意的;深思熟虑的"],["delicate","adj.","精致的;脆弱的;微妙的"],["democracy","n.","民主"],["density","n.","密度;稠密"],
    ["denounce","v.","谴责;告发"],["depict","v.","描绘;描述"],["deposit","n.","存款;押金 v.存放;沉淀"],["deprive","v.","剥夺"],
    ["deputy","n.","副手;代理人"],["derive","v.","源自;获得"],["descend","v.","下降;下来"],["designate","v.","指定;任命"],
    ["despise","v.","鄙视;看不起"],["deteriorate","v.","恶化;退化"],["deviation","n.","偏离;偏差"],["diagnose","v.","诊断"],
    ["dictate","v.","口授;支配;命令"],["differentiate","v.","区分;区别"],["diffuse","v.","扩散;传播"],["dilemma","n.","困境;进退两难"],
    ["dim","adj.","昏暗的;模糊的"],["dimension","n.","尺寸;维度;方面"],["diminish","v.","减少;缩小"],["diplomatic","adj.","外交的;圆滑的"],
    ["disable","v.","使残废;使无效"],["discard","v.","丢弃;抛弃"],["discern","v.","辨别;看出"],["disclose","v.","揭露;透露"],
    ["discourse","n.","话语;论述"],["discrepancy","n.","差异;不一致"],["disguise","v.","伪装 n.伪装"],["disgust","n./v.","厌恶"],
    ["dismay","n./v.","沮丧;惊愕"],["dispatch","v.","派遣;发送"],["disperse","v.","驱散;散开"],["displace","v.","取代;使离开原位"],
    ["disposal","n.","处理;处置"],["dispute","n./v.","争论;纠纷"],["dissolve","v.","溶解;解散"],["distill","v.","蒸馏;提炼"],
    ["distort","v.","歪曲;扭曲"],["distract","v.","使分心;分散(注意力)"],["distress","n.","痛苦;危难 v.使痛苦"],["doctrine","n.","教义;学说"],
    ["domain","n.","领域;领土"],["domestic","adj.","国内的;家庭的;驯养的"],["dominant","adj.","占主导地位的"],["doom","n.","厄运 v.注定"],
    ["dose","n.","剂量;一剂"],["drain","v.","排干;耗尽 n.排水管"],["drastic","adj.","激烈的;严厉的"],["drift","v.","漂流;飘移 n.趋势"],
    ["dubious","adj.","可疑的;怀疑的"],["duplicate","v.","复制 n.复制品"],["durable","adj.","耐用的;持久的"],["duration","n.","持续时间"],
    ["dwell","v.","居住;细想"],["dynamic","adj.","动态的;有活力的"],["earnest","adj.","认真的;诚恳的"],["eccentric","adj.","古怪的"],
    ["edible","adj.","可食用的"],["eject","v.","驱逐;喷出"],["elaborate","adj.","精心制作的;详尽的"],["elapse","v.","(时间)流逝"],
    ["elastic","adj.","有弹性的 n.松紧带"],["eligible","adj.","有资格的;合适的"],["elite","n.","精英;上层人士"],["eloquent","adj.","雄辩的;有说服力的"],
    ["embark","v.","着手;开始(embark on)"],["embody","v.","体现;包含"],["embrace","v.","拥抱;欣然接受"],["eminent","adj.","杰出的;显赫的"],
    ["empirical","adj.","经验的;实证的"],["encompass","v.","包含;包围"],["endeavor","n./v.","努力;尽力"],["endorse","v.","支持;背书"],
    ["endure","v.","忍受;持久"],["enforce","v.","执行;强制"],["enlighten","v.","启发;开导"],["enroll","v.","注册;入学;招收"],
    ["ensure","v.","确保;保证"],["entail","v.","需要;使承担"],["enterprise","n.","企业;事业;进取心"],["entitle","v.","给…权利;给…题名"],
    ["entity","n.","实体;独立存在物"],["entrepreneur","n.","企业家"],["envisage","v.","设想;展望"],["episode","n.","一集;一段经历;插曲"],
    ["equity","n.","公平;股本"],["equivalent","adj.","等同的 n.等同物"],["erase","v.","擦除;抹去"],["erect","v.","建立;竖立 adj.直立的"],
    ["erode","v.","侵蚀;腐蚀"],["erroneous","adj.","错误的"],["erupt","v.","爆发;喷发"],["essence","n.","本质;精髓"],
    ["estate","n.","房地产;庄园"],["esteem","n./v.","尊重;尊敬"],["eternal","adj.","永恒的"],["ethnic","adj.","种族的;民族的"],
    ["evacuate","v.","疏散;撤离"],["evade","v.","逃避;规避"],["evaporate","v.","蒸发;消失"],["evoke","v.","唤起;引起"],
    ["exceptional","adj.","杰出的;异常的"],["excess","n.","过量 adj.过量的"],["exclaim","v.","呼喊;惊叫"],["exclusive","adj.","独有的;排他的"],
    ["execute","v.","执行;处决"],["exemplify","v.","例证;是…的典型"],["exempt","adj.","被免除的 v.免除"],["exert","v.","施加;运用(exert influence)"],
    ["exhaust","v.","耗尽;使精疲力竭 n.废气"],["exile","n./v.","流放;放逐"],["exotic","adj.","异国情调的;奇异的"],["expedition","n.","远征;探险(队)"],
    ["expel","v.","开除;驱逐"],["expend","v.","花费;消耗"],["expertise","n.","专门知识;专长"],["expire","v.","到期;期满;去世"],
    ["explicit","adj.","明确的;直言的"],["exploit","v.","开发;利用;剥削"],["exquisite","adj.","精致的;优美的"],["extinct","adj.","灭绝的;绝种的"],
    ["extract","v.","提取;拔出 n.摘录"],["extravagant","adj.","奢侈的;过度的"],["fabricate","v.","捏造;制造"],["facet","n.","方面;小平面"],
    ["facilitate","v.","促进;使便利"],["faculty","n.","全体教员;才能"],["fade","v.","褪色;消失"],["faint","adj.","模糊的;虚弱的 v.昏倒"],
    ["feasible","adj.","可行的"],["federal","adj.","联邦的"],["feeble","adj.","虚弱的;无力的"],["fertile","adj.","肥沃的;多产的"],
    ["fiber","n.","纤维"],["fiction","n.","小说;虚构"],["fiscal","adj.","财政的"],["flaw","n.","缺陷;瑕疵"],
    ["flee","v.","逃跑;逃避"],["fling","v.","猛扔;抛"],["flourish","v.","繁荣;茂盛"],["fluctuate","v.","波动;起伏"],
    ["forerunner","n.","先驱;前兆"],["foresee","v.","预见;预知"],["forge","v.","锻造;伪造;前进"],["formidable","adj.","强大的;令人敬畏的;难对付的"],
    ["formulate","v.","制定;系统阐述"],["foster","v.","培养;促进;收养"],["fraction","n.","小部分;分数"],["fragile","adj.","脆弱的;易碎的"],
    ["fragment","n.","碎片;片段"],["framework","n.","框架;体系"],["frantic","adj.","狂乱的;发狂似的"],["fraud","n.","欺诈;骗子"],
    ["friction","n.","摩擦(力);冲突"],["fringe","n.","边缘;刘海"],["frustrate","v.","使沮丧;挫败"],["fume","n.","烟;气体 v.发怒"],
    ["furious","adj.","狂怒的;猛烈的"],["furnish","v.","供应;为…配备家具"],["fusion","n.","融合;熔化"],["gamble","v./n.","赌博;冒险"],
    ["gaze","v./n.","凝视;注视"],["gear","n.","齿轮;装备 v.使适应"],["gender","n.","性别"],["genetic","adj.","基因的;遗传的"],
    ["gigantic","adj.","巨大的"],["glare","v.","怒视;刺眼地发光"],["gleam","v.","闪光;闪烁"],["glide","v.","滑行;滑动"],
    ["glimpse","n./v.","一瞥;瞥见"],["gloomy","adj.","阴郁的;昏暗的"],["gorgeous","adj.","华丽的;极好的"],["gossip","n.","流言;闲谈"],
    ["grace","n.","优雅;恩惠"],["grain","n.","谷物;颗粒"],["graphic","adj.","图表的;生动的"],["gratitude","n.","感激"],
    ["gravity","n.","重力;严重性"],["grease","n.","油脂 v.涂油"],["grief","n.","悲伤;悲痛"],["grim","adj.","严峻的;冷酷的"],
    ["grind","v.","磨碎;磨光"],["gross","adj.","总的;毛的;粗俗的"],["grumble","v.","抱怨;嘟囔"],["guideline","n.","指导方针;准则"],
    ["halt","v./n.","停止;暂停"],["hamper","v.","妨碍;阻碍"],["harbor","n.","港口 v.怀有;庇护"],["harden","v.","(使)变硬"],
    ["harsh","adj.","严酷的;刺耳的"],["haste","n.","匆忙;仓促"],["hatch","v.","孵化;策划"],["hazard","n.","危险;危害"],
    ["headquarters","n.","总部;指挥部"],["heave","v.","举起;起伏"],["hence","adv.","因此;从此"],["heritage","n.","遗产;传统"],
    ["hierarchy","n.","等级制度"],["hinder","v.","阻碍;妨碍"],["hollow","adj.","空心的;空洞的"],["homogeneous","adj.","同质的;同类的"],
    ["horizon","n.","地平线;视野"],["hostile","adj.","敌对的;不友善的"],["humble","adj.","谦逊的;卑微的"],["humiliate","v.","羞辱"],
    ["hurl","v.","猛投;猛掷"],["hypothesis","n.","假设;假说"],["identical","adj.","完全相同的"],["ideology","n.","意识形态;思想体系"],
    ["ignorant","adj.","无知的;不知道的"],["illuminate","v.","照亮;阐明"],["illusion","n.","错觉;幻觉"],["immerse","v.","沉浸;使浸没"],
    ["immune","adj.","免疫的;不受影响的"],["impair","v.","损害;削弱"],["impart","v.","传授;告知"],["imperative","adj.","必要的;祈使的"],
    ["impetus","n.","推动力;促进"],["implement","v.","实施;执行 n.工具"],["implicit","adj.","含蓄的;不言明的"],["impose","v.","强加;征税"],
    ["impulse","n.","冲动;脉冲"],["inaccessible","adj.","难以接近的;无法到达的"],["incentive","n.","激励;刺激"],["incidence","n.","发生率;影响范围"],
    ["inclination","n.","倾向;爱好"],["incline","v.","倾向;倾斜"],["incur","v.","招致;遭受"],["indifferent","adj.","漠不关心的;冷淡的"],
    ["indignant","adj.","愤慨的;义愤的"],["indispensable","adj.","必不可少的"],["induce","v.","引诱;导致;诱发"],["indulge","v.","沉溺;放纵"],
    ["inertia","n.","惯性;惰性"],["infect","v.","感染;传染"],["inferior","adj.","较低的;较差的"],["infinite","adj.","无限的;无穷的"],
    ["inflation","n.","通货膨胀"],["ingenious","adj.","灵巧的;巧妙的"],["inhabit","v.","居住于"],["inherent","adj.","固有的;内在的"],
    ["inherit","v.","继承"],["inhibit","v.","抑制;阻止"],["initiate","v.","开始;发起;使入门"],["inject","v.","注射;注入"],
    ["innovation","n.","创新;革新"],["innumerable","adj.","无数的"],["insight","n.","洞察力;深刻见解"],["inspiration","n.","灵感;鼓舞"],
    ["install","v.","安装;任命"],["instinct","n.","本能;直觉"],["institution","n.","机构;制度"],["integrate","v.","整合;融入"],
    ["integrity","n.","正直;完整"],["intellectual","adj.","智力的 n.知识分子"],["intelligence","n.","智力;情报"],["intelligible","adj.","可理解的"],
    ["intent","n.","意图 adj.专注的"],["interior","adj.","内部的 n.内部"],["intermediate","adj.","中级的;中间的"],["internal","adj.","内部的;国内的"],
    ["intersection","n.","交叉路口;交叉"],["interval","n.","间隔;幕间休息"],["intervene","v.","干预;介入"],["intimate","adj.","亲密的;私人的"],
    ["intricate","adj.","错综复杂的"],["intuition","n.","直觉"],["invariably","adv.","始终如一地;总是"],["inventory","n.","库存;清单"],
    ["invert","v.","使倒置;反转"],["irony","n.","反讽;讽刺"],["irrespective","adj.","不顾的;不考虑的"],["irrigate","v.","灌溉"],
    ["irritate","v.","激怒;刺激"],["ivory","n.","象牙"],["jail","n.","监狱"],["jeopardize","v.","危及;损害"],
    ["jerk","v.","猛拉 n.急拉"],["joint","adj.","联合的 n.关节;接头"],["jolly","adj.","快活的"],["justify","v.","证明…正当;为…辩护"],
    ["juvenile","adj.","青少年的 n.少年"],["kidnap","v.","绑架"],["kin","n.","亲属"],["knot","n.","结 v.打结"],
    ["landscape","n.","风景;景观"],["lapse","n.","失误;流逝"],["latent","adj.","潜在的;潜伏的"],["latitude","n.","纬度"],
    ["latter","adj.","后者的"],["laundry","n.","洗衣店;要洗的衣服"],["lay","v.","放置;产(卵)"],["layer","n.","层;层次"],
    ["layout","n.","布局;版面"],["leak","v.","漏;泄露 n.漏洞"],["ledge","n.","壁架;岩石突出部"],["legacy","n.","遗产;遗留"],
    ["legislation","n.","立法;法规"],["legitimate","adj.","合法的;正当的"],["leisure","n.","闲暇;空闲"],["lenient","adj.","宽大的;仁慈的"],
    ["levy","v.","征收;征税"],["liable","adj.","有责任的;易患…的"],["liberal","adj.","开明的;自由的"],["liberty","n.","自由;自由权"],
    ["likelihood","n.","可能性"],["limb","n.","肢;树枝"],["limitation","n.","限制;局限"],["linear","adj.","线性的;直线的"],
    ["linger","v.","徘徊;逗留;磨蹭"],["literacy","n.","读写能力"],["literal","adj.","字面的;逐字的"],["lobby","n.","大厅;游说团体 v.游说"],
    ["locomotive","n.","机车;火车头"],["longitude","n.","经度"],["lubricate","v.","润滑"],["lucrative","adj.","赚钱的;利润丰厚的"],
    ["lump","n.","块;肿块"],["lure","v.","引诱 n.诱惑力"],["luxury","n.","奢侈(品)"],["magnify","v.","放大;夸大"],
    ["magnitude","n.","巨大;重要性;震级"],["maintenance","n.","维护;保养"],["majesty","n.","陛下;庄严"],["manifest","adj.","明显的 v.表明;显现"],
    ["manipulate","v.","操纵;操控"],["manuscript","n.","手稿;原稿"],["margin","n.","页边空白;差额;余地"],["marine","adj.","海洋的"],
    ["marvelous","adj.","非凡的;绝妙的"],["masculine","adj.","男性的;阳刚的"],["mask","v.","掩盖 n.面具"],["massacre","n./v.","大屠杀"],
    ["mat","n.","垫子"],["maternal","adj.","母亲的;母方的"],["mediate","v.","调解;斡旋"],["medieval","adj.","中世纪的"],
    ["melody","n.","旋律;曲调"],["memorize","v.","记住;熟记"],["menace","n.","威胁;危险 v.威胁"],["merge","v.","合并;融合"],
    ["merit","n.","优点;价值 v.值得"],["metropolitan","adj.","大都市的"],["midst","n.","中间;当中"],["migrate","v.","迁徙;移居"],
    ["mingle","v.","混合;交际"],["miserable","adj.","悲惨的;痛苦的"],["misfortune","n.","不幸;灾祸"],["mobilize","v.","动员;调动"],
    ["mock","v.","嘲笑 adj.模拟的"],["mode","n.","方式;模式"],["modest","adj.","谦虚的;适度的"],["momentum","n.","势头;动量"],
    ["monetary","adj.","货币的;金融的"],["monopoly","n.","垄断"],["monotonous","adj.","单调的"],["monument","n.","纪念碑;遗迹"],
    ["morale","n.","士气;斗志"],["mortal","adj.","致命的;终有一死的"],["mortgage","n.","抵押贷款"],["motif","n.","主题;图案"],
    ["motion","n.","运动;动作 v.示意"],["motivate","v.","激励;驱动"],["mould","n.","模具;霉菌 v.塑造"],["mount","v.","登上;增加 n.山"],
    ["mourn","v.","哀悼;悲叹"],["multitude","n.","大量;众多"],["municipal","adj.","市政的"],["murmur","v./n.","低语;咕哝"],
    ["muscular","adj.","肌肉的;强壮的"],["mute","adj.","沉默的;哑的"],["mutter","v.","咕哝;抱怨"],["naive","adj.","天真的;幼稚的"],
    ["naked","adj.","赤裸的;无遮盖的"],["namely","adv.","即;也就是"],["nap","n.","小睡"],["narrate","v.","叙述;讲述"],
    ["nasty","adj.","令人厌恶的;下流的;恶劣的"],["naval","adj.","海军的"],["navigation","n.","导航;航海"],["necessitate","v.","使成为必要"],
    ["negligible","adj.","微不足道的"],["nominal","adj.","名义上的;象征性的"],["nominate","v.","提名;任命"],["nonetheless","adv.","尽管如此"],
    ["norm","n.","标准;规范"],["notable","adj.","显著的;著名的"],["notify","v.","通知;告知"],["notion","n.","概念;观念;想法"],
    ["notorious","adj.","臭名昭著的"],["nourish","v.","滋养;养育"],["novelty","n.","新奇(的事物)"],["nuisance","n.","令人讨厌的人或物"],
    ["numerical","adj.","数字的;数值的"],["nurture","v.","养育;培养"],["obedience","n.","服从;顺从"],["obese","adj.","肥胖的"],
    ["obligation","n.","义务;责任"],["obscure","adj.","模糊的;晦涩的 v.使模糊"],["obstacle","n.","障碍;障碍物"],["occupy","v.","占据;使忙碌"],
    ["odds","n.","可能性;几率;困难"],["offend","v.","冒犯;违反"],["offset","v.","抵消;补偿"],["offspring","n.","后代;子女"],
    ["omit","v.","省略;遗漏"],["opaque","adj.","不透明的;难懂的"],["oppress","v.","压迫;压抑"],["optimal","adj.","最佳的"],
    ["orient","v.","使适应;确定方向"],["originate","v.","起源于;创始"],["ornament","n.","装饰品 v.装饰"],["orthodox","adj.","正统的;传统的"],
    ["oust","v.","驱逐;罢黜"],["outbreak","n.","爆发;突然发生"],["outfit","n.","全套装备;服装"],["outlet","n.","出口;插座;发泄途径"],
    ["outlook","n.","观点;展望;前景"],["outrage","n.","愤怒;暴行 v.激怒"],["outskirts","n.","郊区;市郊"],["overall","adj.","总的;全面的"],
    ["overlap","v./n.","重叠;交叉"],["overlook","v.","忽视;俯瞰"],["overtake","v.","超过;突然降临"],["overthrow","v.","推翻;颠覆"],
    ["overwhelm","v.","压倒;使不知所措"],["owe","v.","欠;归功于"],["ozone","n.","臭氧"],["panic","n./v.","恐慌;惊慌"],
    ["paradox","n.","悖论;自相矛盾"],["parallel","adj.","平行的 n.相似处"],["parameter","n.","参数;界限"],["parcel","n.","包裹"],
    ["parliament","n.","议会;国会"],["partial","adj.","部分的;偏袒的"],["participant","n.","参与者"],["particle","n.","微粒;粒子"],
    ["partition","n.","分隔;隔墙"],["pastime","n.","消遣;娱乐"],["pasture","n.","牧场;草地"],["patent","n.","专利 adj.专利的"],
    ["pathetic","adj.","可怜的;可悲的"],["patriot","n.","爱国者"],["patron","n.","赞助人;老主顾"],["peak","n.","山顶;顶峰 v.达到顶峰"],
    ["penalty","n.","处罚;罚金"],["pendulum","n.","钟摆;摇摆不定的事"],["penetrate","v.","穿透;渗入"],["pension","n.","养老金;退休金"],
    ["perceive","v.","察觉;认为"],["peril","n.","危险;极大危险"],["perish","v.","死亡;毁灭;腐烂"],["perpetual","adj.","永久的;不断的"],
    ["perplex","v.","使困惑;使复杂化"],["persecute","v.","迫害;骚扰"],["persevere","v.","坚持不懈;锲而不舍"],["personnel","n.","人员;人事部门"],
    ["perspective","n.","视角;透视图"],["pertinent","adj.","相关的;切题的"],["pervade","v.","弥漫;遍布"],["petition","n.","请愿书 v.请愿"],
    ["petty","adj.","琐碎的;小气的"],["phase","n.","阶段;时期"],["philosophy","n.","哲学;人生哲学"],["physical","adj.","身体的;物理的"],
    ["physician","n.","内科医生"],["pilgrim","n.","朝圣者"],["plague","n.","瘟疫;灾害 v.折磨"],["plausible","adj.","貌似合理的"],
    ["plea","n.","恳求;辩护"],["plead","v.","恳求;辩护"],["pledge","n./v.","誓言;保证;抵押"],["plight","n.","困境;苦境"],
    ["plot","n.","情节;阴谋 v.密谋"],["plunge","v.","投入;跳入;骤降"],["poise","n.","沉着;优雅 v.使平衡"],["poke","v.","戳;捅"],
    ["polar","adj.","极地的;截然相反的"],["ponder","v.","沉思;仔细考虑"],["portion","n.","一部分;一份"],["portray","v.","描绘;扮演"],
    ["postpone","v.","推迟;延期"],["potent","adj.","有力的;效力大的"],["practitioner","n.","从业者;执业者"],["preach","v.","布道;宣扬;劝诫"],
    ["precede","v.","先于;在…之前"],["precedent","n.","先例;惯例"],["precipitate","v.","促成;使沉淀"],["predecessor","n.","前任;前辈;前身"],
    ["predominant","adj.","主要的;占优势的"],["premise","n.","前提;房屋"],["premium","n.","保险费;额外费用 adj.高价的"],["prescribe","v.","开处方;规定"],
    ["prestige","n.","威望;声望"],["presume","v.","假定;推测"],["pretext","n.","借口;托辞"],["prevail","v.","盛行;占上风;获胜"],
    ["prevalent","adj.","流行的;普遍的"],["prey","n.","猎物 v.捕食"],["prick","v.","刺;扎"],["primitive","adj.","原始的;简陋的"],
    ["priority","n.","优先(权);优先事项"],["privacy","n.","隐私;独处"],["probe","v.","探查;探究 n.探测器"],["proceed","v.","继续进行;着手"],
    ["proclaim","v.","宣告;声明"],["proficiency","n.","熟练;精通"],["profound","adj.","深刻的;深远的"],["prolong","v.","延长;拉长"],
    ["prominent","adj.","杰出的;显著的;凸出的"],["promising","adj.","有前途的;有希望的"],["prone","adj.","易于…的;俯卧的"],["propaganda","n.","宣传"],
    ["propel","v.","推进;驱动"],["prophet","n.","先知;预言者"],["proponent","n.","支持者;提倡者"],["prose","n.","散文"],
    ["prospective","adj.","未来的;预期的"],["prosper","v.","繁荣;兴旺"],["provoke","v.","激怒;激起;挑衅"],["proximity","n.","接近;邻近"],
    ["prudent","adj.","谨慎的;精明的"],["psychology","n.","心理学;心理"],["punctual","adj.","准时的"],["puppet","n.","木偶;傀儡"],
    ["purity","n.","纯净;纯洁"],["pursuit","n.","追求;追赶;职业"],["qualitative","adj.","定性的;质量的"],["quantify","v.","量化"],
    ["quantitative","adj.","定量的"],["queer","adj.","奇怪的;可疑的"],["quench","v.","解(渴);熄灭"],["quest","n.","寻求;追求"],
    ["questionnaire","n.","问卷;调查表"],["quiver","v.","颤抖;抖动"],["radical","adj.","激进的;根本的"],["raid","n./v.","突袭;搜查"],
    ["rally","v.","集合;恢复 n.集会"],["random","adj.","随机的;任意的"],["ratify","v.","批准;签署认可"],["rational","adj.","理性的;合理的"],
    ["ravage","v.","蹂躏;毁坏"],["realm","n.","领域;王国"],["rear","n.","后部 adj.后面的 v.抚养"],["reassure","v.","使安心;安慰"],
    ["rebellion","n.","叛乱;反抗"],["rebuke","v./n.","斥责;谴责"],["recede","v.","后退;逐渐减弱"],["recipient","n.","接受者;收件人"],
    ["reciprocal","adj.","相互的;互惠的"],["reckless","adj.","鲁莽的;不顾后果的"],["reckon","v.","认为;估计"],["reclaim","v.","取回;开垦;回收"],
    ["reconcile","v.","调和;使和解"],["recreation","n.","娱乐;消遣"],["recruit","v.","招募;招聘 n.新兵"],["rectify","v.","纠正;矫正"],
    ["recur","v.","再发生;复发"],["recycle","v.","回收利用"],["redundant","adj.","多余的;被裁员的"],["refine","v.","精炼;提炼;改进"],
    ["refrain","v.","克制;避免"],["refuge","n.","避难所;庇护"],["refund","n./v.","退款"],["refute","v.","驳斥;反驳"],
    ["regime","n.","政权;政体"],["reign","n./v.","统治;支配"],["reimburse","v.","偿还;报销"],["reinforce","v.","加强;增援"],
    ["reiterate","v.","重申;反复说"],["rejoice","v.","欣喜;高兴"],["relay","v.","转播;传达 n.接力赛"],["reliance","n.","依赖;依靠"],
    ["relish","v.","享受;品味 n.滋味;乐趣"],["remainder","n.","剩余部分"],["remedy","n.","补救办法;药物"],["remnant","n.","残余;剩余"],
    ["renaissance","n.","复兴;文艺复兴"],["rend","v.","撕裂;扯碎"],["render","v.","使成为;给予;提供"],["renew","v.","更新;续期;恢复"],
    ["renounce","v.","宣布放弃;与…断绝关系"],["renovate","v.","翻新;修复"],["repel","v.","击退;排斥;使厌恶"],["repent","v.","后悔;悔悟"],
    ["repertoire","n.","全部剧目;全部技能"],["repetition","n.","重复;反复"],["repression","n.","镇压;抑制"],["reproach","v./n.","责备;指责"],
    ["reproduce","v.","繁殖;复制"],["reptile","n.","爬行动物"],["resemblance","n.","相似;相似之处"],["resemble","v.","与…相似"],
    ["resent","v.","愤恨;怨恨"],["reservation","n.","预订;保留意见;保护区"],["reside","v.","居住;存在于"],["residual","adj.","剩余的;残余的"],
    ["resign","v.","辞职;放弃"],["resilient","adj.","有韧性的;能复原的"],["resolution","n.","决心;决议;解决"],["respectable","adj.","体面的;可敬的"],
    ["respective","adj.","各自的;分别的"],["restrain","v.","抑制;阻止;约束"],["resume","v.","重新开始 n.简历"],["retail","n.","零售"],
    ["retaliate","v.","报复;反击"],["retarded","adj.","迟钝的"],["retort","v./n.","反驳;回嘴"],["retrieve","v.","找回;检索"],
    ["retrospect","n.","回顾;追溯"],["revenue","n.","收入;税收"],["revere","v.","尊敬;崇敬"],["revive","v.","复苏;使复兴;使苏醒"],
    ["revolt","v./n.","反抗;起义"],["rhetoric","n.","修辞;花言巧语"],["ridicule","v./n.","嘲笑;奚落"],["rigid","adj.","僵硬的;严格的"],
    ["rigorous","adj.","严格的;严谨的"],["rim","n.","边缘;轮圈"],["riot","n.","暴乱;骚乱"],["rip","v.","撕;撕裂"],
    ["ritual","n.","仪式;例行公事"],["rival","n.","竞争对手 adj.竞争的"],["roar","v./n.","吼叫;轰鸣"],["robust","adj.","强健的;坚固的"],
    ["rot","v.","腐烂;腐坏"],["rotary","adj.","旋转的"],["rough","adj.","粗糙的;粗略的;艰苦的"],["rouse","v.","唤醒;激起"],
    ["route","n.","路线;途径"],["royal","adj.","王室的;皇家的"],["ruthless","adj.","无情的;残忍的"],["sack","n.","麻袋;解雇 v.解雇;劫掠"],
    ["sacred","adj.","神圣的;宗教的"],["safeguard","v.","保护;捍卫 n.保护措施"],["saint","n.","圣人;圣徒"],["sanction","n./v.","制裁;批准"],
    ["sane","adj.","神志正常的;明智的"],["sarcastic","adj.","讽刺的;挖苦的"],["satire","n.","讽刺;讽刺文学"],["saturate","v.","使饱和;浸透"],
    ["savage","adj.","野蛮的;凶猛的"],["scar","n.","伤疤 v.留下伤痕"],["scarce","adj.","缺乏的;稀少的"],["scenario","n.","情景;方案;剧本"],
    ["scent","n.","气味;香味;线索"],["scorn","n./v.","轻蔑;鄙视"],["scramble","v.","攀登;争抢; scramble eggs炒蛋"],["scrap","n.","碎片 v.废弃"],
    ["scrape","v.","刮;擦;勉强维持"],["scratch","v.","抓;挠;划伤"],["scrutiny","n.","细看;审查"],["sculpture","n.","雕塑(作品)"],
    ["seal","n.","印章;海豹 v.密封"],["seclude","v.","使隔离;使隐居"],["segregate","v.","隔离;分开"],["seminar","n.","研讨会;研究班"],
    ["sensation","n.","感觉;轰动"],["sentiment","n.","情感;情绪;观点"],["sequence","n.","顺序;一系列"],["serene","adj.","宁静的;安详的"],
    ["sergeant","n.","警官;军士"],["serial","adj.","连续的;系列的"],["setback","n.","挫折;倒退"],["settlement","n.","解决;定居点;结算"],
    ["severe","adj.","严重的;严厉的;剧烈的"],["shabby","adj.","破旧的;衣衫褴褛的;卑鄙的"],["shaft","n.","轴;柄;矿井"],["shallow","adj.","浅的;肤浅的"],
    ["shatter","v.","粉碎;使震惊"],["sheer","adj.","完全的;纯粹的;陡峭的"],["shrewd","adj.","精明的;机敏的"],["shrink","v.","收缩;退缩"],
    ["shrug","v.","耸肩"],["shuttle","n.","穿梭;航天飞机;班车"],["siege","n.","围攻;围困"],["signify","v.","表示;意味着"],
    ["simultaneous","adj.","同时的"],["sin","n.","罪;罪过"],["sincere","adj.","真诚的"],["skeptical","adj.","怀疑的"],
    ["skim","v.","略读;撇去"],["skull","n.","头骨;颅骨"],["slack","adj.","松弛的;懈怠的"],["slap","v.","掌击;拍打"],
    ["slash","v.","猛砍;大幅削减"],["slaughter","v./n.","屠杀;屠宰"],["slavery","n.","奴隶制;奴役"],["sledge","n.","雪橇"],
    ["slender","adj.","苗条的;纤细的"],["slice","n.","薄片 v.切成薄片"],["slide","v.","滑动 n.滑梯"],["slim","adj.","苗条的;微薄的"],
    ["slogan","n.","口号;标语"],["slope","n.","斜坡;山坡"],["slot","n.","狭槽;空位;时段"],["slump","v.","暴跌;衰退;重重坐下"],
    ["smash","v.","打碎;猛击;击溃"],["smuggle","v.","走私;偷运"],["snap","v.","折断;突然崩溃;拍照"],["snatch","v.","抢夺;一把抓住"],
    ["soar","v.","翱翔;猛增;高飞"],["sober","adj.","清醒的;冷静的"],["solemn","adj.","庄严的;严肃的"],["solicit","v.","请求;征求;招揽"],
    ["solidarity","n.","团结;一致"],["solitary","adj.","孤独的;独居的;单一的"],["solo","n.","独奏;独唱 adj.单独的"],["soluble","adj.","可溶的;可解决的"],
    ["soothe","v.","安慰;抚慰;缓和"],["sore","adj.","疼痛的;恼火的"],["soul","n.","灵魂;心灵;精神"],["sovereign","adj.","拥有主权的 n.君主"],
    ["spacious","adj.","宽敞的"],["span","n.","跨度;一段时间 v.跨越"],["spark","n.","火花 v.激发;引发"],["sparkle","v.","闪耀;闪烁"],
    ["sparse","adj.","稀疏的;稀少的"],["spawn","v.","产卵;引发;大量产生"],["specialty","n.","专业;专长;特产"],["specimen","n.","标本;样本"],
    ["spectacle","n.","景象;奇观;眼镜(复)"],["spectator","n.","观众;旁观者"],["spectrum","n.","光谱;范围;系列"],["speculate","v.","推测;投机"],
    ["sphere","n.","球体;领域;范围"],["spill","v.","溢出;洒出"],["spin","v.","旋转;纺(纱)"],["spiral","n.","螺旋 adj.螺旋的 v.盘旋"],
    ["spite","n.","恶意;怨恨(in spite of 尽管)"],["splash","v.","溅;泼"],["splendid","adj.","壮丽的;极好的"],["sponge","n.","海绵"],
    ["spontaneous","adj.","自发的;自然的"],["sprinkle","v.","撒;洒"],["sprout","v.","发芽;长出"],["squad","n.","小队;班"],
    ["squeeze","v.","挤压;挤;压缩"],["stab","v.","刺;戳"],["stability","n.","稳定(性)"],["stagger","v.","蹒跚;使震惊;错开"],
    ["stagnant","adj.","停滞的;不流动的"],["stain","v.","染色;玷污 n.污点"],["stake","n.","桩;赌注;股份 v.以…打赌"],["stale","adj.","不新鲜的;陈腐的"],
    ["stalk","n.","茎 v.跟踪;悄悄接近"],["stall","n.","货摊; stalls前排座位 v.熄火;拖延"],["stammer","v.","口吃;结巴"],["staple","n.","主食;主要产品 adj.主要的"],
    ["startle","v.","使吃惊;使吓一跳"],["starve","v.","挨饿;饿死"],["static","adj.","静止的;静电的"],["stationary","adj.","静止的;不动的"],
    ["statistics","n.","统计(学);统计数据"],["statue","n.","雕像;塑像"],["stature","n.","身高;声望"],["statute","n.","法规;法令"],
    ["steer","v.","驾驶;引导"],["stem","n.","茎;词干 v.阻止;起源于"],["stereotype","n.","刻板印象;成见"],["sterile","adj.","无菌的;不育的;贫瘠的"],
    ["stern","adj.","严厉的;严肃的 n.船尾"],["steward","n.","乘务员;管家"],["sticky","adj.","粘的;棘手的"],["stiff","adj.","僵硬的;生硬的"],
    ["sting","v.","刺;叮;刺痛"],["stipulate","v.","规定;明确要求"],["stitch","n.","针脚;缝线 v.缝"],["stoop","v.","弯腰;屈尊"],
    ["stout","adj.","结实的;肥胖的;坚固的"],["straightforward","adj.","直截了当的;简单的"],["strain","v.","拉紧;过度劳累 n.压力;品种"],["strand","n.","(绳)股;岸 v.使搁浅"],
    ["strap","n.","带子 v.捆扎"],["straw","n.","稻草;吸管"],["stray","v.","走失;偏离 adj.走失的"],["stream","n.","小溪;溪流 v.流动"],
    ["strengthen","v.","加强;巩固"],["strenuous","adj.","费力的;艰苦的;积极的"],["stride","v.","大步走 n.大步;进步"],["strife","n.","冲突;斗争"],
    ["strike","v.","打击;罢工;突然想到"],["string","n.","细绳;一串;弦"],["strip","v.","剥去;剥夺 n.狭长地带"],["strive","v.","努力;奋斗"],
    ["stroke","n.","中风;一击;抚摸;笔画"],["stroll","v./n.","散步;闲逛"],["stubborn","adj.","固执的;顽固的"],["stumble","v.","绊倒;结巴地说"],
    ["stun","v.","使震惊;使昏迷"],["sturdy","adj.","结实的;坚固的;强健的"],["subdue","v.","制服;征服;抑制"],["subjective","adj.","主观的"],
    ["submarine","n.","潜水艇"],["submerge","v.","淹没;浸没"],["subordinate","adj.","从属的 n.下属"],["subscribe","v.","订阅;捐助;同意"],
    ["subsequent","adj.","随后的;后来的"],["subsidy","n.","补贴;津贴"],["subsist","v.","生存;维持生活"],["substantial","adj.","大量的;实质的;坚固的"],
    ["substitute","n.","替代品 v.代替"],["subtle","adj.","微妙的;精细的;敏锐的"],["subtract","v.","减去"],["suburb","n.","郊区"],
    ["succession","n.","连续;一连串;继任"],["successive","adj.","连续的;接连的"],["sue","v.","起诉;控告"],["suffice","v.","足够;满足"],
    ["suicide","n.","自杀"],["suit","n.","套装;诉讼 v.适合"],["sum","n.","总数;金额 v.总结"],["summon","v.","召唤;传唤;鼓起(勇气)"],
    ["superb","adj.","极好的;卓越的"],["superficial","adj.","肤浅的;表面的"],["superfluous","adj.","多余的;过剩的"],["superintendent","n.","主管;监督人"],
    ["superior","adj.","优越的;上级的 n.上级"],["supersonic","adj.","超音速的"],["superstition","n.","迷信"],["supervise","v.","监督;管理"],
    ["supplement","n.","补充;增刊 v.补充"],["suppress","v.","压制;抑制;镇压"],["supreme","adj.","最高的;至高的"],["surge","v./n.","汹涌;激增"],
    ["surgeon","n.","外科医生"],["surmount","v.","克服;登上"],["surpass","v.","超过;胜过"],["surrender","v./n.","投降;屈服"],
    ["susceptible","adj.","易受影响的;易患…的"],["suspend","v.","暂停;悬挂;使停职"],["suspicion","n.","怀疑;猜疑"],["swamp","n.","沼泽 v.淹没;使应接不暇"],
    ["swap","v./n.","交换;互换"],["sway","v.","摇摆;影响"],["swell","v.","肿胀;膨胀"],["swerve","v.","突然转向"],
    ["swing","v.","摆动;摇摆 n.秋千"],["switch","n.","开关;转变 v.转换"],["symmetry","n.","对称(性)"],["symposium","n.","专题讨论会;研讨会"],
    ["synthesis","n.","综合;合成"],["systematic","adj.","系统的;有条理的"],["tactic","n.","策略;战术"],["tangle","v./n.","缠结;纠结"],
    ["tangible","adj.","有形的;切实的"],["tardy","adj.","迟到的;缓慢的"],["tariff","n.","关税;价目表"],
    ["tease","v.","取笑;逗弄"],["tedious","adj.","冗长乏味的"],["temper","n.","脾气;情绪 v.缓和"],["temperament","n.","气质;性情"],
    ["tempo","n.","速度;节奏"],["tempt","v.","引诱;吸引"],["tenant","n.","房客;佃户"],["tendency","n.","倾向;趋势"],
    ["tender","adj.","温柔的;嫩的;疼痛的"],["terminal","adj.","末端的;晚期的 n.航站楼;终端"],["terminate","v.","终止;结束"],["terrain","n.","地形;地势"],
    ["terrific","adj.","极好的;可怕的"],["terrify","v.","使恐惧;恐吓"],["territory","n.","领土;领域"],["testify","v.","作证;证明"],
    ["testimony","n.","证词;证据"],["textile","n.","纺织品"],["texture","n.","质地;纹理"],["theft","n.","盗窃;偷窃"],
    ["thereby","adv.","因此;从而"],["thermal","adj.","热的;热量的"],["thesis","n.","论文;论点"],["thirst","n.","口渴;渴望"],
    ["thorough","adj.","彻底的;仔细的"],["threshold","n.","门槛;开端;阈值"],["thrift","n.","节俭;节约"],["thrill","n.","激动;兴奋 v.使激动"],
    ["thrive","v.","兴旺;茁壮成长"],["throne","n.","王位;宝座"],["throng","n.","人群 v.蜂拥"],["thrust","v.","猛推;刺 n.推力"],
    ["thunder","n.","雷;雷声 v.打雷"],["tick","n.","滴答声;勾号 v.滴答作响"],["tide","n.","潮汐;潮流"],["tidy","adj.","整洁的 v.整理"],
    ["tile","n.","瓷砖;瓦片"],["tilt","v.","倾斜"],["timber","n.","木材;木料"],["timid","adj.","胆小的;羞怯的"],
    ["tissue","n.","组织;纸巾"],["toil","n./v.","苦工;辛勤劳作"],["token","n.","代币;象征;礼券"],["toll","n.","通行费;伤亡人数;代价"],
    ["torrent","n.","急流;洪流"],["torture","v./n.","折磨;拷打"],["toss","v.","扔;抛;辗转"],["tournament","n.","锦标赛;联赛"],
    ["tow","v.","拖;牵引"],["toxic","adj.","有毒的"],["tract","n.","大片土地;地带;短文"],["tragedy","n.","悲剧;惨剧"],
    ["trail","n.","小径;踪迹 v.拖"],["trait","n.","特征;特点"],["tramp","v.","跋涉 n.流浪汉"],["tranquil","adj.","平静的;安宁的"],
    ["transaction","n.","交易;业务"],["transcend","v.","超越;胜过"],["transcript","n.","成绩单;抄本"],["transient","adj.","短暂的;临时的"],
    ["transit","n.","运输;公共交通;过境"],["transition","n.","过渡;转变"],["transmission","n.","传播;传送"],["transparent","adj.","透明的;显而易见的"],
    ["transplant","v.","移植;移栽"],["traverse","v.","横穿;穿越"],["treacherous","adj."," treacherous险恶的;背叛的"],["treaty","n.","条约;协定"],
    ["tremble","v.","颤抖;发抖"],["tremendous","adj.","巨大的;极好的"],["trench","n.","沟;战壕"],["tribe","n.","部落;族群"],
    ["tribute","n.","颂词;贡品"],["trifle","n.","琐事;少量 v.轻视"],["trig","adj.","整洁的"],["trim","v.","修剪;削减 adj.整洁的"],
    ["triumph","n.","胜利;成功 v.获胜"],["trivial","adj.","琐碎的;微不足道的"],["tropic","n.","热带地区;回归线"],["troupe","n.","剧团;歌舞团"],
    ["trunk","n.","树干;行李箱;象鼻"],["tuck","v.","塞进;卷起"],["tug","v.","用力拉 n.拖船"],["tuition","n.","学费;讲授"],
    ["tumble","v.","跌倒;翻滚;暴跌"],["tumult","n.","骚乱;吵闹"],["tune","n.","曲调 v.调音;调整"],["turbulent","adj.","动荡的;湍流的"],
    ["turmoil","n.","混乱;骚动"],["turnover","n.","营业额;人员流动率"],["tutor","n.","导师;家教 v.辅导"],["twilight","n.","暮色;黄昏;衰落时期"],
    ["twist","v.","扭;扭曲;缠绕"],["ultimate","adj.","最终的;根本的"],["unanimous","adj.","一致同意的"],["uncover","v.","揭露;发现;揭开"],
    ["undergraduate","n.","本科生"],["undermine","v.","逐渐削弱;破坏"],["unemployment","n.","失业(率)"],["unfold","v.","展开;展现"],
    ["unify","v.","统一;使一致"],["unilateral","adj.","单方面的"],["unprecedented","adj.","史无前例的"],["unravel","v.","解开;弄清;瓦解"],
    ["uphold","v.","支持;维护;维持"],["uproar","n.","骚动;喧嚣"],["upset","v.","使不安;打乱 adj.难过的"],["urban","adj.","城市的"],
    ["urge","v.","敦促 n.强烈欲望"],["usage","n.","用法;使用;惯例"],["utensil","n.","器具;器皿"],["utilitarian","adj.","实用的;功利主义的"],
    ["utility","n.","效用;公用事业"],["utmost","adj.","极度的;最大的 n.极限"],["utter","v.","说出;发出(声音) adj.完全的"],["vaccinate","v.","给…接种疫苗"],
    ["validity","n.","有效性;正当性"],["valor","n.","英勇"],["vanish","v.","消失;突然不见"],["vanity","n.","虚荣(心)"],
    ["vapor","n.","蒸汽;水汽"],["variable","adj.","多变的 n.变量"],["variation","n.","变化;变异;变奏"],["vegetation","n.","植被;植物"],
    ["velocity","n.","速度;速率"],["venerable","adj.","德高望重的;令人尊敬的"],["vengeance","n.","报复;复仇"],["vent","n.","通风口;出口 v.发泄"],
    ["ventilate","v.","使通风;公开讨论"],["verdict","n.","裁决;定论"],["verge","n.","边缘;边界(on the verge of 濒于)"],["versatile","adj.","多才多艺的;多用途的"],
    ["verse","n.","诗;韵文;诗节"],["vertical","adj.","垂直的"],["vessel","n.","船;容器;血管"],["veteran","n.","老兵;老手"],
    ["veto","n./v.","否决(权)"],["vex","v.","使烦恼;使恼怒"],["viable","adj.","可行的;能存活的"],["vibrate","v.","振动;颤动"],
    ["vice","n.","恶习;邪恶;副职(前缀)"],["vicinity","n.","附近;邻近地区"],["vicious","adj.","恶毒的;凶残的;剧烈的"],["vigor","n.","活力;精力"],
    ["vigorous","adj.","充满活力的;有力的"],["villa","n.","别墅"],["vinegar","n.","醋"],["violate","v.","违反;侵犯"],
    ["virgin","n.","处女 adj.未开发的;原始的"],["virtually","adv.","实际上;几乎"],["virus","n.","病毒"],["vista","n.","远景;展望"],
    ["visual","adj.","视觉的"],["vocal","adj.","嗓音的;畅所欲言的"],["vocational","adj.","职业的"],["void","adj.","空的;无效的 n.空虚"],
    ["volatile","adj.","易变的;动荡的;挥发性的"],["volume","n.","卷;册;音量;体积;数量"],["voluntary","adj.","自愿的;志愿的"],["voucher","n.","代金券;凭证"],
    ["vulgar","adj.","粗俗的;庸俗的"],["vulnerable","adj.","易受伤害的;脆弱的"],["wade","v.","涉水;跋涉"],["wagon","n.","四轮马车;货车"],
    ["wake","v.","唤醒;醒来 n.航迹;守灵"],["wander","v.","漫步;游荡;走神"],["ward","n.","病房;区;被监护人 v.避开(ward off)"],["warehouse","n.","仓库"],
    ["warrant","n.","授权令;理由 v.保证;使正当"],["watertight","adj.","防水的;无懈可击的"],["wax","n.","蜡 v.上蜡;渐圆"],["weary","adj.","疲倦的;厌倦的"],
    ["weave","v.","编织;编造"],["wedge","n.","楔子 v.楔入;挤入"],["weird","adj.","古怪的;离奇的"],["weld","v.","焊接;熔接"],
    ["wharf","n.","码头"],["whereby","adv.","凭此;借以"],["whirl","v.","旋转;回旋 n.旋转"],["wholesale","n.","批发 adj.大规模的"],
    ["wicked","adj.","邪恶的;淘气的"],["wield","v.","挥舞;行使(权力)"],["withdraw","v.","撤回;提款;退出"],["withhold","v.","拒绝给予;隐瞒"],
    ["withstand","v.","承受;抵挡"],["wither","v.","枯萎;凋谢"],["witty","adj.","诙谐的;机智的"],["worship","v./n.","崇拜;敬奉"],
    ["wound","n.","伤口 v.使受伤"],["wrath","n.","愤怒;暴怒"],["wreck","v.","破坏;使失事 n.残骸"],["wrench","v.","猛扭;使痛苦 n.扳手"],
    ["wrestle","v.","摔跤;搏斗;努力解决"],["wrinkle","n.","皱纹 v.起皱"],["yacht","n.","游艇;快艇"],["yell","v.","叫喊;呼喊"],
    ["yield","v.","屈服;产出 n.产量;收益"],["zeal","n.","热情;狂热"],["zealous","adj.","热心的;热情的"],["zigzag","n.","之字形 v.曲折前进"],
    ["zone","n.","地区;地带"],["zoom","v.","急速移动;猛涨"]
  ];
  function push(arr, lv){ for (var i = 0; i < arr.length; i++) { W.list.push({ w: arr[i][0], p: arr[i][1], m: arr[i][2], lv: lv }); } }
  push(L1, 1); push(L2, 2); push(L3, 3);
  W.tiers.forEach(function (t) { t.count = W.list.filter(function (x) { return x.lv === t.id; }).length; });
  W.total = W.list.length;
  g.ED = g.ED || {}; g.ED.vocab = W;
})(window);
